SELECT SCENARIOS.PLANNEDFOR FROM TASKS
INNER JOIN AER
ON
  AER.ID = TASKS.PARENT
  INNER JOIN SCENARIOS
  ON
    SCENARIOS.SCENARIOTYPE='BTC' AND
    SCENARIOS.STATUS = 'Done' AND
    SCENARIOS.ID=AER.PARENT
    INNER JOIN STORIES
    ON
      STORIES.ID = SCENARIOS.PARENT AND      
      STORIES.STATUS != 'Rejected'
      INNER JOIN FEATURES
      ON
        FEATURES.ID = STORIES.PARENT AND
        CAST(FEATURES.GRR_ID_ AS NUMBER) > 0
        INNER JOIN PLAN
        ON
          SCENARIOS.PLANNEDFOR = PLAN.SPRINT
          INNER JOIN BTC
          ON
            BTC.CALC_SPRINT = PLAN.QC_SPRINT
          GROUP BY SCENARIOS.PLANNEDFOR
/**

select
  SCENARIOS.PLANNEDFOR AS SPRINT, SUM(TASKS.ACTUAL) AS EFFORT, COUNT(QCBTC.DEFECTID) AS BTCDEFECTS, COUNT(QCUT.DEFECTID) AS UTDEFECTS 
FROM TASKS
INNER JOIN AER
ON
  AER.ID = TASKS.PARENT
  INNER JOIN SCENARIOS
  ON
    SCENARIOS.ID=AER.PARENT 
   INNER JOIN STORIES
ON
                                STORIES.ID = SCENARIOS.PARENT and
                                SCENARIOS.SCENARIOTYPE='BTC' and
                                STORIES.STATUS != 'Rejected' and
                                SCENARIOS.STATUS = 'Done'
                                INNER JOIN FEATURES
                                ON
                                                FEATURES.ID=STORIES.PARENT and
                                                CAST(FEATURES.GRR_ID_ AS NUMBER) > 0
  JOIN QCBTC
  ON
   QCBTC.SPRINT=SCENARIOS.PLANNEDFOR AND
  JOIN QCUT
  ON
   QCUT.SPRINT=SCENARIOS.PLANNEDFOR AND
GROUP BY SCENARIOS.PLANNEDFOR

**/