SELECT TIMESTAMP, (CAST(FGCT AS DOUBLE) / CAST(TIMESTAMP AS DOUBLE) * 100) AS FGCPCT,
(CAST(YGCT AS DOUBLE) / CAST(TIMESTAMP AS DOUBLE) * 100) AS YGCPCT,
(CAST(GCT AS DOUBLE) / CAST(TIMESTAMP AS DOUBLE) * 100) AS GCPCT
FROM CSV