<script>
<%
  println new File("javascript/tether/latest/tether.min.js").text
  println new File("javascript/jquery/latest/jquery.min.js").text
  println new File("javascript/jquery-ui/latest/jquery-ui.min.js").text
  println new File("javascript/bootstrap3/latest/bootstrap.min.js").text
  println new File("javascript/underscore/latest/underscore-min.js").text
  println new File("javascript/dexjs/latest/dex.js").text
%>
</script>