/* JS */ gapi.loaded_0(function(_){var window=this;
_.m=function(a){throw a;};_.p=void 0;_.r=!0;_.s=null;_.u=!1;_.aa=function(){return function(a){return a}};_.v=function(){return function(){}};_.ba=function(a){return function(c){this[a]=c}};_.y=function(a){return function(){return this[a]}};_.ca=function(a){return function(){return a}};_.C=function(a,c,f){a=a.split(".");f=f||_.D;!(a[0]in f)&&f.execScript&&f.execScript("var "+a[0]);for(var g;a.length&&(g=a.shift());)!a.length&&(0,_.F)(c)?f[g]=c:f=f[g]?f[g]:f[g]={}};
_.da=function(a){var c=typeof a;if("object"==c)if(a){if(a instanceof window.Array)return"array";if(a instanceof window.Object)return c;var f=window.Object.prototype.toString.call(a);if("[object Window]"==f)return"object";if("[object Array]"==f||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==f||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==c&&"undefined"==typeof a.call)return"object";return c};_.F=function(a){return a!==_.p};_.fa=function(a){return"array"==(0,_.da)(a)};_.ga=function(a){var c=(0,_.da)(a);return"array"==c||"object"==c&&"number"==typeof a.length};_.ha=function(a){return"string"==typeof a};_.ia=function(a){return"function"==(0,_.da)(a)};_.ja=function(a){var c=typeof a;return"object"==c&&a!=_.s||"function"==c};_.ka=function(a,c,f){return a.call.apply(a.bind,arguments)};
_.la=function(a,c,f){a||(0,_.m)((0,window.Error)());if(2<arguments.length){var g=window.Array.prototype.slice.call(arguments,2);return function(){var f=window.Array.prototype.slice.call(arguments);window.Array.prototype.unshift.apply(f,g);return a.apply(c,f)}}return function(){return a.apply(c,arguments)}};_.G=function(a,c,f){_.G=window.Function.prototype.bind&&-1!=window.Function.prototype.bind.toString().indexOf("native code")?_.ka:_.la;return _.G.apply(_.s,arguments)};
_.ma=function(a,c){var f=window.Array.prototype.slice.call(arguments,1);return function(){var c=window.Array.prototype.slice.call(arguments);c.unshift.apply(c,f);return a.apply(this,c)}};_._DumpException=function(a){(0,_.m)(a)};_.na=_.na||{};_.D=this;_.oa="closure_uid_"+window.Math.floor(2147483648*window.Math.random()).toString(36);_.pa=window.Date.now||function(){return+new window.Date}; window.Function.prototype.bind=window.Function.prototype.bind||function(a,c){if(1<arguments.length){var f=window.Array.prototype.slice.call(arguments,1);f.unshift(this,a);return _.G.apply(_.s,f)}return(0,_.G)(this,a)};
_.ra=window.gapi||{};_.ta=window.gadgets||{};_.H=window.osapi=window.osapi||{};
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{jsonpOverride:_.u},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.u},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.u},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/u/:session_index:/_/pages/badge"},":socialhost:":"https://plusone.google.com",card:{params:{s:"#",userid:"&"},url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton"},
plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator"}},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"chili.people.list":_.r,"pos.plusones.list":_.r,"pos.plusones.get":_.r,"chili.people.get":_.r,"pos.plusones.insert":_.r,"chili.activities.list":_.r,"pos.plusones.delete":_.r,"chili.activities.get":_.r,
"chili.activities.search":_.r,"pos.plusones.getSignupState":_.r},requestCache:{enabled:_.r},versions:{chili:"v1",pos:"v1"},rpc:"/rpc",root:"https://www.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:_.r},transport:{isProxyShared:_.r},xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:_.u}},drive_saver:{driveUrl:"https://drive.google.com"}});

window.___jsl=window.___jsl||{};(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"onload"}});
_.I=function(a,c,f){return a[c]=a[c]||f};_.va=function(a){return"function"===typeof a};_.wa=function(a){return(0,window.String)(a).replace(_.xa,"&amp;").replace(_.ya,"&lt;").replace(_.za,"&gt;").replace(_.Aa,"&quot;").replace(_.Ba,"&#39;")};_.L=function(){var a;if((a=window.Object.create)&&_.Ca.test(a))a=a(_.s);else{a={};for(var c in a)a[c]=_.p}return a};_.Da=function(a,c){return window.Object.prototype.hasOwnProperty.call(a,c)};_.Ea=function(a,c){a=a||{};for(var f in a)(0,_.Da)(a,f)&&(c[f]=a[f])};
_.Fa=function(a,c){a||(0,_.m)((0,window.Error)(c||""))};_.Ga=function(a,c,f){var g=(0,window.RegExp)("([#].*&|[#])"+c+"=([^&#]*)","g");c=(0,window.RegExp)("([?#].*&|[?#])"+c+"=([^&#]*)","g");if(a=a&&(g.exec(a)||c.exec(a)))try{f=(0,window.decodeURIComponent)(a[2])}catch(h){}return f};_.Ha=function(a){a=a.match(_.Ia);var c=(0,_.L)();c.uc=a[1];c.jb=a[3]?[a[3]]:[];c.Mf=a[5]?[a[5]]:[];return c};
_.Ja=function(a){a=a?a.split("&"):[];for(var c=[],f=0;f<a.length;f++){var g=a[f].split("=",2);c.push([(0,window.decodeURIComponent)(g[0]),(0,window.decodeURIComponent)(g[1])])}return c};_.Ka=function(a){return a.uc+(0<a.jb.length?"?"+a.jb.join("&"):"")+(0<a.Mf.length?"#"+a.Mf.join("&"):"")};_.La=function(a){var c=[];if(a)for(var f in a)(0,_.Da)(a,f)&&a[f]!=_.s&&c.push((0,window.encodeURIComponent)(f)+"="+(0,window.encodeURIComponent)(a[f]));return c};
_.Ma=function(a,c,f){a=(0,_.Ha)(a);a.jb.push.apply(a.jb,(0,_.La)(c));a.Mf.push.apply(a.Mf,(0,_.La)(f));return(0,_.Ka)(a)};_.Na=function(a,c){var f=a.createElement("div"),g=a.createElement("a");g.href=c;f.appendChild(g);f.innerHTML=f.innerHTML;c=(0,window.String)(f.firstChild.href);f.parentNode&&f.parentNode.removeChild(f);return c};_.Oa=function(a){for(;a.firstChild;)a.removeChild(a.firstChild)};_.Pa=function(a){return!_.Qa.dpo?(0,_.Ga)(a,"jsh",_.Qa.h):_.Qa.h};
_.Ra=function(a){return(0,_.Ga)(a,"_bsh",_.Qa.bsh)};_.Sa=function(){return(0,_.I)(_.Qa,"WI",(0,_.L)())};_.Ta=function(){return _.Qa.ssfn};_.Ua=function(){return _.Qa.onl};_.Va=function(a){_.Qa.onl=a};_.Wa=function(a){var c=window.___jsl=window.___jsl||{};c[a]=c[a]||[];return c[a]};_.Xa=function(a){var c=window.___jsl=window.___jsl||{};c.cfg=!a&&c.cfg||{};return c.cfg};_.Ya=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};
_.Za=function(a,c){if(c)for(var f in c)c.hasOwnProperty(f)&&(a[f]&&c[f]&&"object"===typeof a[f]&&"object"===typeof c[f]&&!(0,_.Ya)(a[f])&&!(0,_.Ya)(c[f])?(0,_.Za)(a[f],c[f]):c[f]&&"object"===typeof c[f]?(a[f]=(0,_.Ya)(c[f])?[]:{},(0,_.Za)(a[f],c[f])):a[f]=c[f])};
_.$a=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);var c;try{c=window.JSON.parse(a)}catch(f){}if("object"===typeof c)return c;try{c=(new window.Function("return ("+a+"\n)"))()}catch(g){}if("object"===typeof c)return c;try{c=(new window.Function("return ({"+a+"\n})"))()}catch(h){}return"object"===typeof c?c:{}}};
_.ab=function(a){(0,_.Xa)(_.r);var c=window.___gcfg,f=(0,_.Wa)("cu");if(c&&c!==window.___gu){var g={};(0,_.Za)(g,c);f.push(g);window.___gu=c}var c=(0,_.Wa)("cu"),h=window.document.scripts||window.document.getElementsByTagName("script")||[],g=[],l=[];l.push.apply(l,(0,_.I)(_.Qa,"us",[]));for(var n=0;n<h.length;++n)for(var q=h[n],t=0;t<l.length;++t)q.src&&0==q.src.indexOf(l[t])&&g.push(q);0==g.length&&(0<h.length&&h[h.length-1].src)&&g.push(h[h.length-1]);for(h=0;h<g.length;++h)g[h].getAttribute("gapi_processed")||
(g[h].setAttribute("gapi_processed",_.r),(l=g[h])?(n=l.nodeType,l=3==n||4==n?l.nodeValue:l.textContent||l.innerText||l.innerHTML||""):l=_.p,(l=(0,_.$a)(l))&&c.push(l));a&&(g={},(0,_.Za)(g,a),f.push(g));g=(0,_.Wa)("cd");a=0;for(c=g.length;a<c;++a)(0,_.Za)((0,_.Xa)(),g[a]);g=(0,_.Wa)("ci");a=0;for(c=g.length;a<c;++a)(0,_.Za)((0,_.Xa)(),g[a]);a=0;for(c=f.length;a<c;++a)(0,_.Za)((0,_.Xa)(),f[a])};
_.N=function(a,c){if(!a)return(0,_.Xa)();for(var f=a.split("/"),g=(0,_.Xa)(),h=0,l=f.length;g&&"object"===typeof g&&h<l;++h)g=g[f[h]];return h===f.length&&g!==_.p?g:c};_.bb=function(a,c){var f=a;if("string"===typeof a){for(var g=f={},h=a.split("/"),l=0,n=h.length;l<n-1;++l)var q={},g=g[h[l]]=q;g[h[l]]=c}(0,_.ab)(f)};_.cb=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),(0,_.I)(_.Qa,"ci",[]).push(a),window.__GOOGLEAPIS=_.p)}; _.O=function(a,c){c="function"==typeof _.db&&(0,_.db)(a,c)||c;(0,_.C)(a,c,_.p)};
_.eb=window;_.fb=window.document;_.Ca=/\[native code\]/;_.xa=/&/g;_.ya=/</g;_.za=/>/g;_.Aa=/"/g;_.Ba=/'/g;_.gb=(0,_.I)(_.eb,"gapi",{});_.Ia=/^([^?#]*)(\?([^#]*))?(\#(.*))?$/;_.Qa=(0,_.I)(_.eb,"___jsl",(0,_.L)());(0,_.I)(_.Qa,"I",0);(0,_.I)(_.Qa,"hel",10);_.cb&&(0,_.cb)();(0,_.ab)();(0,_.O)("gapi.config.get",_.N);(0,_.O)("gapi.config.update",_.bb);


_.mb={go:{},I:{}};_.nb={go:{},I:{}};


_.Q=_.Q||{};
_.Q=_.Q||{};_.Q.ug=function(a,c,f){for(var g=[],h=2,l=arguments.length;h<l;++h)g.push(arguments[h]);return function(){for(var f=g.slice(),h=0,l=arguments.length;h<l;++h)f.push(arguments[h]);return c.apply(a,f)}};_.Q.gf=function(a){var c,f,g={};for(c=0;f=a[c];++c)g[f]=f;return g};

_.vb=function(a,c){return window.String.fromCharCode(c)};_.Q=_.Q||{};_.wb={"0":_.u,10:_.r,13:_.r,34:_.r,39:_.r,60:_.r,62:_.r,92:_.r,8232:_.r,8233:_.r,65282:_.r,65287:_.r,65308:_.r,65310:_.r,65340:_.r};_.Q.escape=function(a,c){if(a){if("string"===typeof a)return _.Q.Jf(a);if("array"===typeof a)for(var f=0,g=a.length;f<g;++f)a[f]=_.Q.escape(a[f]);else if("object"===typeof a&&c){f={};for(g in a)a.hasOwnProperty(g)&&(f[_.Q.Jf(g)]=_.Q.escape(a[g],_.r));return f}}return a}; _.Q.Jf=function(a){if(!a)return a;for(var c=[],f,g,h=0,l=a.length;h<l;++h)f=a.charCodeAt(h),g=_.wb[f],g===_.r?c.push("&#",f,";"):g!==_.u&&c.push(a.charAt(h));return c.join("")};_.Q.pv=function(a){return!a?a:a.replace(/&#([0-9]+);/g,_.vb)};

_.zb=_.zb||{};_.zb.Ip=function(){var a=0,c=0;window.self.innerHeight?(a=window.self.innerWidth,c=window.self.innerHeight):window.document.documentElement&&window.document.documentElement.clientHeight?(a=window.document.documentElement.clientWidth,c=window.document.documentElement.clientHeight):window.document.body&&(a=window.document.body.clientWidth,c=window.document.body.clientHeight);return{width:a,height:c}};

_.Ab=function(a,c){window.getComputedStyle(a,"").getPropertyValue(c).match(/^([0-9]+)/);return(0,window.parseInt)(window.RegExp.$1,10)};_.zb=_.zb||{};
_.zb.Hh=function(){var a=_.zb.Ip().height,c=window.document.body,f=window.document.documentElement;if("CSS1Compat"===window.document.compatMode&&f.scrollHeight)return f.scrollHeight!==a?f.scrollHeight:f.offsetHeight;if(0<=window.navigator.userAgent.indexOf("AppleWebKit")){a=0;for(c=[window.document.body];0<c.length;){var g=c.shift(),f=g.childNodes;if("undefined"!==typeof g.style){var h=g.style.overflowY;h||(h=(h=window.document.defaultView.getComputedStyle(g,_.s))?h.overflowY:_.s);if("visible"!=h&&
"inherit"!=h&&(h=g.style.height,h||(h=(h=window.document.defaultView.getComputedStyle(g,_.s))?h.height:""),0<h.length&&"auto"!=h))continue}for(g=0;g<f.length;g++){h=f[g];if("undefined"!==typeof h.offsetTop&&"undefined"!==typeof h.offsetHeight)var l=h.offsetTop+h.offsetHeight+(0,_.Ab)(h,"margin-bottom"),a=window.Math.max(a,l);c.push(h)}}return a+(0,_.Ab)(window.document.body,"border-bottom")+(0,_.Ab)(window.document.body,"margin-bottom")+(0,_.Ab)(window.document.body,"padding-bottom")}if(c&&f)return g= f.scrollHeight,h=f.offsetHeight,f.clientHeight!==h&&(g=c.scrollHeight,h=c.offsetHeight),g>a?g>h?g:h:g<h?g:h};

_.Vc=window.gapi&&window.gapi.util||{};
_.Wc=_.Vc=_.Vc||{};_.Xc={sj:"bsh",vj:"h"};window.___jsl=window.___jsl||{};_.Wc.fh={b:function(){return window.___jsl[_.Xc.sj]},fk:function(){return window.___jsl[_.Xc.vj]},Vi:function(a){window.___jsl[_.Xc.sj]=a},Tr:function(a){window.___jsl[_.Xc.vj]=a}};

if(window.JSON&&window.JSON.parse&&window.JSON.stringify){_.ob=function(a){return this[a]};_.pb=/___$/;_.P={parse:function(a){try{return window.JSON.parse(a)}catch(c){return _.u}},stringify:function(a){function c(a){return f.call(this,a,_.ob)}var f=window.JSON.stringify,g=window.Array.prototype.toJSON&&'"[{\\"x\\": 1}]"'===f([{x:1}])?c:f;try{return g(a,function(a,c){return!_.pb.test(a)?c:_.p})}catch(h){return _.s}}}};
if(!window.JSON||!window.JSON.parse||!window.JSON.stringify)_.P=function(){function a(a){return 10>a?"0"+a:a}function c(a){var h,l,n;h=/[\"\\\x00-\x1f\x7f-\x9f]/g;switch(typeof a){case "string":return h.test(a)?'"'+a.replace(h,function(a){var c=f[a];if(c)return c;c=a.charCodeAt();return"\\u00"+window.Math.floor(c/16).toString(16)+(c%16).toString(16)})+'"':'"'+a+'"';case "number":return(0,window.isFinite)(a)?(0,window.String)(a):"null";case "boolean":case "null":return(0,window.String)(a);case "object":if(!a)return"null";
h=[];if("number"===typeof a.length&&!a.propertyIsEnumerable("length")){n=a.length;for(l=0;l<n;l+=1)h.push(c(a[l])||"null");return"["+h.join(",")+"]"}for(l in a)!/___$/.test(l)&&a.hasOwnProperty(l)&&"string"===typeof l&&(n=c(a[l]))&&h.push(c(l)+":"+n);return"{"+h.join(",")+"}"}return""}window.Date.prototype.toJSON=function(){return[this.getUTCFullYear(),"-",a(this.getUTCMonth()+1),"-",a(this.getUTCDate()),"T",a(this.getUTCHours()),":",a(this.getUTCMinutes()),":",a(this.getUTCSeconds()),"Z"].join("")};
var f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return{stringify:c,parse:function(a){return/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))?eval("("+a+")"):_.u}}}();
_.P.Zj=function(a){var c={};if(a===_.s||a===_.p)return c;for(var f in a)if(a.hasOwnProperty(f)){var g=a[f];_.s===g||_.p===g||(c[f]="string"===typeof g?g:_.P.stringify(g))}return c};(0,_.O)("gadgets.json.flatten",_.P.Zj);(0,_.O)("gadgets.json.parse",_.P.parse);(0,_.O)("gadgets.json.stringify",_.P.stringify);(0,_.O)("gadgets.json.flatten",_.P.Zj);(0,_.O)("gadgets.json.parse",_.P.parse);(0,_.O)("gadgets.json.stringify",_.P.stringify);

_.Q=_.Q||{};_.Bb=[];_.Q.ev=function(a){_.Bb.push(a)};_.Q.jv=function(){for(var a=0,c=_.Bb.length;a<c;++a)_.Bb[a]()};
_.xb=function(a){for(var c=0;c<this.length;c++)if(this[c]===a)return c;return-1};_.Q=_.Q||{};_.yb=_.s;
_.Q.na=function(a){var c="undefined"===typeof a;if(_.yb!==_.s&&c)return _.yb;var f={};a=a||window.document.location.href;var g=a.indexOf("?"),h=a.indexOf("#");a=(-1===h?a.substr(g+1):[a.substr(g+1,h-g-1),"&",a.substr(h+1)].join("")).split("&");for(var g=window.decodeURIComponent?window.decodeURIComponent:window.unescape,h=0,l=a.length;h<l;++h){var n=a[h].indexOf("=");if(-1!==n){var q=a[h].substring(0,n),n=a[h].substring(n+1),n=n.replace(/\+/g," ");try{f[q]=g(n)}catch(t){}}}c&&(_.yb=f);return f};_.Q.na();
(0,_.O)("gadgets.util.getUrlParameters",_.Q.na);
_.Db=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;_.Db&&(0,_.bb)((0,_.Db)());_.Cb={N:function(a,c,f){f&&f((0,_.N)())},get:function(a){return(0,_.N)(a)},update:function(a,c){c&&(0,_.m)("Config replacement is not supported");(0,_.bb)(a)},da:(0,_.v)()};
(0,_.O)("gadgets.config.register",_.Cb.N);(0,_.O)("gadgets.config.get",_.Cb.get);(0,_.O)("gadgets.config.init",_.Cb.da);(0,_.O)("gadgets.config.update",_.Cb.update);
_.Eb=_.Eb||{};_.Eb.Wl=_.s;_.Eb.sl=_.s;_.Eb.ig=_.s;_.Eb.frameElement=_.s;_.Eb=_.Eb||{};
if(!_.Eb.pj){_.Hb=function(a){var c=_.P.parse(a.data);if(c&&c.f){var f=_.R.Wd(c.f);(!_.Fb||!("undefined"!==typeof a.origin?a.origin!==f:a.domain!==/^.+:\/\/([^:]+).*/.exec(f)[1]))&&(0,_.Gb)(c,a.origin)}};_.Fb=_.r;_.Eb.pj={dk:(0,_.ca)("wpm"),b:(0,_.ca)(_.r),da:function(a,c){_.Cb.N("rpc",_.s,function(a){if("true"===(0,window.String)((a&&a.rpc||{}).disableForceSecure))_.Fb=_.u});_.Gb=a;_.Ib=c;"undefined"!=typeof window.addEventListener?window.addEventListener("message",_.Hb,_.u):"undefined"!=typeof window.attachEvent&&
window.attachEvent("onmessage",_.Hb);window.___jsl=window.___jsl||{};var f=window.___jsl;f.RPMQ=f.RPMQ||[];f.RPMQ.push(_.Hb);(0,_.Ib)("..",_.r);return _.r},Zc:function(a){(0,_.Ib)(a,_.r);return _.r},call:function(a,c,f){var g=_.R.Wd(a),h=_.R.Dj(a);g?window.setTimeout(function(){h.postMessage(_.P.stringify(f),g)},0):".."!=a&&(0,_.ua)("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message");return _.r}}};
_.Eb=_.Eb||{};
if(!_.Eb.Lf){_.Jb=_.Eb;_.Mb=function(a,c){function f(){a.apply({},arguments)}_.Kb[c]=_.Kb[c]||f;return _.Lb+"."+c};_.Tb=function(){if(_.Nb===_.s&&window.document.body&&_.Ob){var a=_.Ob+"?cb="+window.Math.random()+"&origin="+_.Pb+"&jsl=1",c=window.document.createElement("div");c.style.height="1px";c.style.width="1px";a='<object height="1" width="1" id="'+_.Qb+'" type="application/x-shockwave-flash"><param name="allowScriptAccess" value="always"></param><param name="movie" value="'+a+'"></param><embed type="application/x-shockwave-flash" allowScriptAccess="always" src="'+
a+'" height="1" width="1"></embed></object>';window.document.body.appendChild(c);c.innerHTML=a;_.Nb=c.firstChild}++_.Rb;_.Sb!==_.s&&(_.Nb!==_.s||50<=_.Rb)?window.clearTimeout(_.Sb):_.Sb=window.setTimeout(_.Tb,100)};_.$b=function(){_.Wb[".."]||((0,_.Xb)(".."),_.Yb++,50<=_.Yb&&_.Zb!==_.s?(window.clearTimeout(_.Zb),_.Zb=_.s):_.Zb=window.setTimeout(_.$b,100))};_.bc=function(){if(_.Nb!==_.s&&_.Nb.setup)for(;0<_.ac.length;){var a=_.ac.shift(),c=a.ks;_.Nb.setup(a.pe,".."===c?_.R.Wg:c,".."===c?"INNER":"OUTER")}_.Sb!==
_.s&&window.clearTimeout(_.Sb);_.Sb=_.s};_.cc=function(){!_.Wb[".."]&&_.Zb===_.s&&(_.Zb=window.setTimeout(_.$b,100))};_.dc=function(a,c,f){c=_.R.Wd(a);var g=_.R.Sd(a);_.Nb["sendMessage_"+(".."===a?_.R.Wg:a)+"_"+g+"_"+(".."===a?"INNER":"OUTER")].call(_.Nb,_.P.stringify(f),c);return _.r};_.gc=function(a,c){var f=_.P.parse(a),g=f._scr;g?((0,_.ec)(g,_.r),_.Wb[g]=_.r,".."!==g&&(0,_.Xb)(g,_.r)):window.setTimeout(function(){(0,_.fc)(f,c)},0)};_.Xb=function(a,c){var f=_.R.Wg,g={};g._scr=c?"..":f;g._pnt=f;
(0,_.dc)(a,f,g)};_.Qb="___xpcswf";_.Ob=_.s;_.hc=_.u;_.fc=_.s;_.ec=_.s;_.Nb=_.s;_.ac=[];_.Sb=_.s;_.Rb=0;_.Yb=0;_.Zb=_.s;_.Wb={};_.Pb=window.location.protocol+"//"+window.location.host;window.___jsl=window.___jsl||{};_.ic=window.___jsl._fm={};_.Lb="___jsl._fm";_.Kb=_.ic;_.Cb.N("rpc",_.s,function(a){_.hc&&(_.Ob=a&&a.rpc&&a.rpc.commSwf||"//xpc.googleusercontent.com/gadgets/xpc.swf")});(0,_.Mb)(_.bc,"ready");(0,_.Mb)(_.cc,"setupDone");(0,_.Mb)(_.gc,"receiveMessage");_.Jb.Lf={dk:(0,_.ca)("flash"),b:(0,_.ca)(_.r), da:function(a,c){_.fc=a;_.ec=c;return _.hc=_.r},Zc:function(a,c){_.ac.push({pe:c,ks:a});_.Nb===_.s&&_.Sb===_.s&&(_.Sb=window.setTimeout(_.Tb,100));return _.r},call:_.dc,lo:_.gc,d:_.bc,i:_.cc}};
if(!window.gadgets||!window.gadgets.rpc){_.qc=function(a,c){if(!_.jc[a]){var f=_.kc;c||(f=_.nc);_.jc[a]=f;for(var g=_.oc[a]||[],h=0;h<g.length;++h){var l=g[h];l.t=_.pc[a];f.call(a,l.f,l)}_.oc[a]=[]}};_.vc=function(a,c,f,g,h){function l(){_.rc=_.r}if(!_.pc[c]||_.pc[c]!==f)(0,_.ua)("Invalid gadgets.rpc token. "+_.pc[c]+" vs "+f),(0,_.sc)(c,2);h.onunload=function(){_.tc[c]&&!_.rc&&((0,_.sc)(c,1),_.R.Ti(c))};_.uc||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",l,_.u):"undefined"!=
typeof window.attachEvent&&window.attachEvent("onunload",l),_.uc=_.r);g=_.P.parse((0,window.decodeURIComponent)(g))};_.yc=function(a,c){if(a&&"string"===typeof a.s&&"string"===typeof a.f&&a.a instanceof window.Array)if(_.pc[a.f]&&_.pc[a.f]!==a.t&&((0,_.ua)("Invalid gadgets.rpc token. "+_.pc[a.f]+" vs "+a.t),(0,_.sc)(a.f,2)),"__ack"===a.s)window.setTimeout(function(){(0,_.qc)(a.f,_.r)},0);else{a.c&&(a.callback=function(c){_.R.call(a.f,(a.g?"legacy__":"")+"__cb",_.s,a.c,c)});if(c){var f=(0,_.wc)(c);
a.origin=c;var g=a.r;if(!g||(0,_.wc)(g)!=f)g=c;a.referer=g}f=(_.xc[a.s]||_.xc[""]).apply(a,a.a);a.c&&"undefined"!==typeof f&&_.R.call(a.f,"__cb",_.s,a.c,f)}};_.wc=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));a=a.substring(0,a.indexOf("://"));var f="",g=c.indexOf(":");if(-1!=g){var h=
c.substring(g+1),c=c.substring(0,g);if("http"===a&&"80"!==h||"https"===a&&"443"!==h)f=":"+h}return a+"://"+c+f};_.zc=function(a){if("/"==a.charAt(0)){var c=a.indexOf("|");return{id:0<c?a.substring(1,c):a.substring(1),origin:0<c?a.substring(c+1):_.s}}return _.s};_.Ac=function(a){if("undefined"===typeof a||".."===a)return window.parent;var c=(0,_.zc)(a);if(c)return window.top.frames[c.id];a=(0,window.String)(a);return(c=window.frames[a])?c:(c=window.document.getElementById(a))&&c.contentWindow?c.contentWindow:
_.s};_.Bc=function(a,c){if(_.tc[a]!==_.r){"undefined"===typeof _.tc[a]&&(_.tc[a]=0);var f=(0,_.Ac)(a);(".."===a||f!=_.s)&&_.kc.Zc(a,c)===_.r?_.tc[a]=_.r:_.tc[a]!==_.r&&10>_.tc[a]++?window.setTimeout(function(){(0,_.Bc)(a,c)},500):(_.jc[a]=_.nc,_.tc[a]=_.r)}};_.Ec=function(a){(a=_.Cc[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a};_.Gc=function(a,c,f){c&&!/http(s)?:\/\/.+/.test(c)&&
(0==c.indexOf("//")?c=window.location.protocol+c:"/"==c.charAt(0)?c=window.location.protocol+"//"+window.location.host+c:-1==c.indexOf("://")&&(c=window.location.protocol+"//"+c));_.Cc[a]=c;"undefined"!==typeof f&&(_.Fc[a]=!!f)};_.Hc=function(a,c){c=c||"";_.pc[a]=(0,window.String)(c);(0,_.Bc)(a,c)};_.Kc=function(a){a=(a.passReferrer||"").split(":",2);_.Ic=a[0]||"none";_.Jc=a[1]||"origin"};_.Lc=function(a){"true"===(0,window.String)(a.useLegacyProtocol)&&(_.kc=_.Eb.ig||_.nc,_.kc.da(_.yc,_.qc))};_.Nc=
function(a,c,f){if(".."===a){var g=f||_.Mc.rpctoken||_.Mc.ifpctok||"";a=function(a){a=a&&a.rpc||{};(0,_.Kc)(a);var f=a.parentRelayUrl||"",f=(0,_.wc)(_.Mc.parent||c)+f;(0,_.Gc)("..",f,"true"===(0,window.String)(a.useLegacyProtocol));(0,_.Lc)(a);(0,_.Hc)("..",g)};!_.Mc.parent&&c?a({}):_.Cb.N("rpc",_.s,a)}else a:{var h=_.s;if("/"!=a.charAt(0)){if(!_.Q)break a;(h=window.document.getElementById(a))||(0,_.m)((0,window.Error)("h`"+a))}var h=h&&h.src,l=c||_.R.ja(h);(0,_.Gc)(a,l);h=_.Q.na(h);(0,_.Hc)(a,f||
h.rpctoken)}};_.xc={};_.Cc={};_.Fc={};_.pc={};_.Oc=0;_.Pc={};_.tc={};_.Mc={};_.jc={};_.oc={};_.Ic=_.s;_.Jc=_.s;_.Qc=window.top!==window.self;_.Rc=window.name;_.sc=(0,_.v)();_.Sc=window.console;_.Tc=_.Sc&&_.Sc.log&&function(a){_.Sc.log(a)}||(0,_.v)();_.Uc=function(a){return function(){(0,_.Tc)(a+": call ignored")}};_.nc={getCode:(0,_.ca)("noop"),isParentVerifiable:(0,_.ca)(_.r),init:(0,_.Uc)("init"),setup:(0,_.Uc)("setup"),call:(0,_.Uc)("call")};_.Q&&(_.Mc=_.Q.na());_.rc=_.u;_.uc=_.u;_.kc=function(){if("flash"==
_.Mc.rpctx)return _.Eb.Lf;if("rmr"==_.Mc.rpctx)return _.Eb.Wl;var a="function"===typeof window.postMessage?_.Eb.pj:"object"===typeof window.postMessage?_.Eb.pj:window.ActiveXObject?_.Eb.Lf?_.Eb.Lf:_.Eb.sl?_.Eb.sl:_.Eb.ig:0<window.navigator.userAgent.indexOf("WebKit")?_.Eb.Wl:"Gecko"===window.navigator.product?_.Eb.frameElement:_.Eb.ig;a||(a=_.nc);return a}();_.xc[""]=function(){(0,_.Tc)("Unknown RPC service: "+this.s)};_.xc.__cb=function(a,c){var f=_.Pc[a];f&&(delete _.Pc[a],f.call(this,c))};_.R=
{Da:function(a){"function"===typeof a.Er&&(_.sc=a.Er)},N:function(a,c){("__cb"===a||"__ack"===a)&&(0,_.m)((0,window.Error)("i"));""===a&&(0,_.m)((0,window.Error)("j"));_.xc[a]=c},Vb:function(a){("__cb"===a||"__ack"===a)&&(0,_.m)((0,window.Error)("k"));""===a&&(0,_.m)((0,window.Error)("l"));delete _.xc[a]},Nl:function(a){_.xc[""]=a},zm:function(){delete _.xc[""]},bk:(0,_.v)(),call:function(a,c,f,g){a=a||"..";var h="..";".."===a?h=_.Rc:"/"==a.charAt(0)&&(h=_.R.ja(window.location.href),h="/"+_.Rc+(h?
"|"+h:""));++_.Oc;f&&(_.Pc[_.Oc]=f);var l={s:c,f:h,c:f?_.Oc:0,a:window.Array.prototype.slice.call(arguments,3),t:_.pc[a],l:!!_.Fc[a]},n;a:if("bidir"===_.Ic||"c2p"===_.Ic&&".."===a||"p2c"===_.Ic&&".."!==a){n=window.location.href;var q="?";if("query"===_.Jc)q="#";else if("hash"===_.Jc)break a;q=n.lastIndexOf(q);q=-1===q?n.length:q;n=n.substring(0,q)}else n=_.s;n&&(l.r=n);".."!==a&&(0,_.zc)(a)==_.s&&!window.document.getElementById(a)||(n=_.jc[a],!n&&(0,_.zc)(a)!==_.s&&(n=_.kc),0===c.indexOf("legacy__")&&
(n=_.kc,l.s=c.substring(8),l.c=l.c?l.c:_.Oc),l.g=_.r,l.r=h,n?(_.Fc[a]&&(n=_.Eb.ig),n.call(a,h,l)===_.u&&(_.jc[a]=_.nc,_.kc.call(a,h,l))):_.oc[a]?_.oc[a].push(l):_.oc[a]=[l])},ik:_.Ec,Mg:_.Gc,Lg:_.Hc,lf:_.Nc,Sd:function(a){return _.pc[a]},Ti:function(a){delete _.Cc[a];delete _.Fc[a];delete _.pc[a];delete _.tc[a];delete _.jc[a]},hk:function(){return _.kc.dk()},Ll:function(a,c){4<a.length?_.kc.lo(a,_.yc):_.vc.apply(_.s,a.concat(c))},Ml:function(a){a.a=window.Array.prototype.slice.call(a.a);window.setTimeout(function(){(0,_.yc)(a)},
0)},ja:_.wc,Wd:function(a){var c=_.s,c=(0,_.Ec)(a);c||(c=(c=(0,_.zc)(a))?c.origin:".."==a?_.Mc.parent:window.document.getElementById(a).src);return(0,_.wc)(c)},da:function(){_.kc.da(_.yc,_.qc)===_.u&&(_.kc=_.nc);_.Qc?(0,_.Nc)(".."):_.Cb.N("rpc",_.s,function(a){a=a.rpc||{};(0,_.Kc)(a);(0,_.Lc)(a)})},Dj:_.Ac,ko:_.zc,b:"__ack",Wg:_.Rc||"..",j:0,i:1,d:2};_.R.da()}else if("undefined"==typeof _.R||!_.R)_.R=window.gadgets.rpc,_.R.Da=_.R.config,_.R.N=_.R.register,_.R.Vb=_.R.unregister,_.R.Nl=_.R.registerDefault,
_.R.zm=_.R.unregisterDefault,_.R.bk=_.R.forceParentVerifiable,_.R.call=_.R.call,_.R.ik=_.R.getRelayUrl,_.R.Mg=_.R.setRelayUrl,_.R.Lg=_.R.setAuthToken,_.R.lf=_.R.setupReceiver,_.R.Sd=_.R.getAuthToken,_.R.Ti=_.R.removeReceiver,_.R.hk=_.R.getRelayChannel,_.R.Ll=_.R.receive,_.R.Ml=_.R.receiveSameDomain,_.R.ja=_.R.getOrigin,_.R.Wd=_.R.getTargetOrigin,_.R.Dj=_.R._getTargetWin,_.R.ko=_.R._parseSiblingId;
(0,_.O)("gadgets.rpc.config",_.R.Da);(0,_.O)("gadgets.rpc.register",_.R.N);(0,_.O)("gadgets.rpc.unregister",_.R.Vb);(0,_.O)("gadgets.rpc.registerDefault",_.R.Nl);(0,_.O)("gadgets.rpc.unregisterDefault",_.R.zm);(0,_.O)("gadgets.rpc.forceParentVerifiable",_.R.bk);(0,_.O)("gadgets.rpc.call",_.R.call);(0,_.O)("gadgets.rpc.getRelayUrl",_.R.ik);(0,_.O)("gadgets.rpc.setRelayUrl",_.R.Mg);(0,_.O)("gadgets.rpc.setAuthToken",_.R.Lg);(0,_.O)("gadgets.rpc.setupReceiver",_.R.lf);
(0,_.O)("gadgets.rpc.getAuthToken",_.R.Sd);(0,_.O)("gadgets.rpc.removeReceiver",_.R.Ti);(0,_.O)("gadgets.rpc.getRelayChannel",_.R.hk);(0,_.O)("gadgets.rpc.receive",_.R.Ll);(0,_.O)("gadgets.rpc.receiveSameDomain",_.R.Ml);(0,_.O)("gadgets.rpc.getOrigin",_.R.ja);(0,_.O)("gadgets.rpc.getTargetOrigin",_.R.Wd);

_.qb=function(a,c){if(!(a<_.sb)&&_._console$$inline_294)if(2===a&&_._console$$inline_294.warn)_._console$$inline_294.warn(c);else if(3===a&&_._console$$inline_294.error)try{_._console$$inline_294.error(c)}catch(f){}else _._console$$inline_294.log&&_._console$$inline_294.log(c)};_.tb=function(a){(0,_.qb)(1,a)};_.ub=function(a){(0,_.qb)(2,a)};_.ua=function(a){(0,_.qb)(3,a)};_.tb.INFO=1;_.tb.WARNING=2;_.tb.NONE=4;_.sb=1; _._console$$inline_294=window.console?window.console:window.opera?window.opera.postError:_.p;

_.Q=_.Q||{};_.Q.ye=function(a,c,f,g){"undefined"!=typeof a.addEventListener?a.addEventListener(c,f,g):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+c,f):(0,_.ub)("cannot attachBrowserEvent: "+c)};_.Q.mr=function(a,c,f,g){a.removeEventListener?a.removeEventListener(c,f,g):a.detachEvent?a.detachEvent("on"+c,f):(0,_.ub)("cannot removeBrowserEvent: "+c)};

_.Zc=function(){function a(){h[0]=1732584193;h[1]=4023233417;h[2]=2562383102;h[3]=271733878;h[4]=3285377520;x=w=0}function c(a){for(var c=n,f=0;64>f;f+=4)c[f/4]=a[f]<<24|a[f+1]<<16|a[f+2]<<8|a[f+3];for(f=16;80>f;f++)c[f]=((c[f-3]^c[f-8]^c[f-14]^c[f-16])<<1|(c[f-3]^c[f-8]^c[f-14]^c[f-16])>>>31)&4294967295;a=h[0];for(var g=h[1],l=h[2],q=h[3],t=h[4],w,x,f=0;80>f;f++)40>f?20>f?(w=q^g&(l^q),x=1518500249):(w=g^l^q,x=1859775393):60>f?(w=g&l|q&(g|l),x=2400959708):(w=g^l^q,x=3395469782),w=((a<<5|a>>>27)&4294967295)+
w+t+x+c[f]&4294967295,t=q,q=l,l=(g<<30|g>>>2)&4294967295,g=a,a=w;h[0]=h[0]+a&4294967295;h[1]=h[1]+g&4294967295;h[2]=h[2]+l&4294967295;h[3]=h[3]+q&4294967295;h[4]=h[4]+t&4294967295}function f(a,f){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var g=[],h=0,n=a.length;h<n;++h)g.push(a.charCodeAt(h));a=g}f||(f=a.length);g=0;if(0==w)for(;g+64<f;)c(a.slice(g,g+64)),g+=64,x+=64;for(;g<f;)if(l[w++]=a[g++],x++,64==w){w=0;for(c(l);g+64<f;)c(a.slice(g,g+64)),g+=64,x+=64}}
function g(){var a=[],g=8*x;56>w?f(q,56-w):f(q,64-(w-56));for(var n=63;56<=n;n--)l[n]=g&255,g>>>=8;c(l);for(n=g=0;5>n;n++)for(var t=24;0<=t;t-=8)a[g++]=h[n]>>t&255;return a}for(var h=[],l=[],n=[],q=[128],t=1;64>t;++t)q[t]=0;var w,x;a();return{reset:a,update:f,Mu:g,Hf:function(){for(var a=g(),c="",f=0;f<a.length;f++)c+="0123456789ABCDEF".charAt(window.Math.floor(a[f]/16))+"0123456789ABCDEF".charAt(a[f]%16);return c}}};

_.$c=function(a){if("complete"===_.fb.readyState)a();else{var c=_.u,f=function(){if(!c)return c=_.r,a.apply(this,arguments)};_.eb.addEventListener?(_.eb.addEventListener("load",f,_.u),_.eb.addEventListener("DOMContentLoaded",f,_.u)):_.eb.attachEvent&&(_.eb.attachEvent("onreadystatechange",function(){"complete"===_.fb.readyState&&f.apply(this,arguments)}),_.eb.attachEvent("onload",f))}};_.bd=function(a){var c=(0,_.Zc)();c.update(a);return c.Hf()};_.cd=window.crypto;
if(_.cd&&"function"==typeof _.cd.getRandomValues)_.ad=function(){var a=new window.Uint32Array(1);_.cd.getRandomValues(a);return(0,window.Number)("0."+a[0])};else{_.dd=(0,_.N)("random/maxObserveMousemove");_.dd==_.s&&(_.dd=-1);_.ed=0;_.fd=window.Math.random();_.gd=1;_.hd=1E6*(window.screen.width*window.screen.width+window.screen.height);_.id=function(a){a=a||window.event;var c=a.screenX+a.clientX<<16,c=c+(a.screenY+a.clientY),c=c*((new window.Date).getTime()%1E6);_.gd=_.gd*c%_.hd;0<_.dd&&++_.ed==_.dd&&
_.Q.mr(window,"mousemove",_.id,_.u)};0!=_.dd&&_.Q.ye(window,"mousemove",_.id,_.u);_.jd=(0,_.bd)(window.document.cookie+"|"+window.document.location+"|"+(new window.Date).getTime()+"|"+_.fd);_.ad=function(){var a=_.gd,a=a+(0,window.parseInt)(_.jd.substr(0,20),16);_.jd=(0,_.bd)(_.jd);return a/(_.hd+window.Math.pow(16,20))}};
(0,_.O)("shindig.random",_.ad);
_.Yc=window.iframer=window.iframer||{};_.S=window.iframes=window.iframes||{};
_.S.yo=function(a,c,f){var g=window.Array.prototype.slice.call(arguments);_.S.gk(function(a){a.sameOrigin&&(g.unshift("/"+a.claimedOpenerId+"|"+window.location.protocol+"//"+window.location.host),_.R.call.apply(_.R,g))})};_.S.jr=function(a,c){_.R.N(a,c)};

_.kd=function(a){var c=(0,_.N)("googleapis.config/sessionIndex");c==_.s&&(c=window.__X_GOOG_AUTHUSER);if(c==_.s){var f=window.google;f&&(c=f.authuser)}c==_.s&&(a==_.s&&(a=window.location.href),c=a?(0,_.Ga)(a,"authuser")||_.s:_.s);return c==_.s?_.s:(0,window.String)(c)};
_.ld=function(a,c,f){a=(0,window.String)(a);if(((0,_.Ga)(a,"authuser")||_.s)!=_.s||((0,_.Ga)(a,"hd")||_.s)!=_.s)return a;c=(0,_.kd)(c);if(f){var g=a,h=g.match(/^((https?:)?\/\/[^\/?#]*)?(\/[^\/?#]+)\/[0-9]+([\/][^?#]*)([?#].*)?$/);if(h&&h[0]){var l=h[1],n=h[4],q=h[5];h[3]=="/"+f&&(g=(l||"")+(n||"/")+(q||""))}if((h=g.match(/^(((https?:)?\/\/[^\/?#]*)([\/][^?#]*)?|([\/][^?#]*))([?#].*)?$/))&&h[0])return l=h[2],a=h[4]||h[5],q=h[6],c!=_.s&&(g=(l||"")+"/"+f+"/"+(0,window.encodeURIComponent)(c)+(a||"/")+
(q||"")),g}f=c==_.s?(0,window.encodeURIComponent)("authuser")+"=0":c.match(/^([-a-z0-9]+[.])+[-a-z0-9]+$/)?[(0,window.encodeURIComponent)("authuser")+"=",(0,window.encodeURIComponent)((0,window.String)(c)),"&"+(0,window.encodeURIComponent)("hd")+"=",(0,window.encodeURIComponent)(c)].join(""):["authuser=",(0,window.encodeURIComponent)(c)].join("");a=a.split("#");c=a[0].indexOf("?");0>c?a[0]=[a[0],"?",f].join(""):(g=[a[0]],c<a[0].length-1&&g.push("&"),g.push(f),a[0]=g.join(""));return g=a.join("#")};
_.md=_.ld;
_.nd=function(){var a=(0,_.Ua)();if(!a){a=(0,_.L)();(0,_.Va)(a);var c=(0,_.L)();a.e=function(a){var g=c[a];g&&(delete c[a],g())};a.a=function(a,g){c[a]=g};a.r=function(a){delete c[a]}}return a};
_.od=function(a,c,f,g,h){var l,n;var q=f.onload;(0,_.va)(q)?((0,_.nd)().a(g,q),n=q):n=_.s;n?((0,_.Fa)(/^\w+$/.test(g),"Unsupported id - "+g),(0,_.nd)(),q='onload="window.___jsl.onl.e(&#34;'+g+'&#34;)"'):q="";try{l=a.createElement('<iframe frameborder="'+(0,_.wa)(f.frameborder)+'" scrolling="'+(0,_.wa)(f.scrolling)+'" '+q+' name="'+(0,_.wa)(f.name)+'"/>')}catch(t){l=a.createElement("iframe"),n&&(l.onload=function(){l.onload=_.s;n.call(this)},(0,_.nd)().r(g))}for(var w in f)a=f[w],"style"===w&&"object"===
typeof a?(0,_.Ea)(a,l.style):_.pd[w]||l.setAttribute(w,(0,window.String)(a));(!h||!h.dontclear)&&(0,_.Oa)(c);c.appendChild(l);l=c.lastChild;f.allowtransparency&&(l.allowTransparency=_.r);return l};
_.qd=function(a,c,f){var g=f||{};f=g.attributes||{};(0,_.Fa)(!g.allowPost||!f.onload,"onload is not supported by post iframe");f=c.ownerDocument||_.fb;var h,l=0;do h=g.id||["I",_.rd++,"_",(new window.Date).getTime()].join("");while(f.getElementById(h)&&5>++l);(0,_.Fa)(5>l,"Error creating iframe id");var n,q=f.location.href,l=(0,_.L)(),t=(0,_.Ra)(q);t&&(l._bsh=t);(q=(0,_.Pa)(q))&&(l.jsh=q);q=(0,_.L)();q.id=h;q.parent=f.location.protocol+"//"+f.location.host;var t=(0,_.Ga)(f.location.href,"id",""),
w=(0,_.Ga)(f.location.href,"pfname","");(t=t?w+"/"+t:"")&&(q.pfname=t);g.hintInFragment?(0,_.Ea)(l,q):n=l;n=(0,_.Ma)(a,n,q);a=(0,_.L)();(0,_.Ea)(_.sd,a);(0,_.Ea)(g.attributes,a);a.name=a.id=h;a.src=n;if((g||{}).allowPost&&2E3<n.length){n=(0,_.Ha)(n);a.src="";a["data-postorigin"]=n.uc;a=(0,_.od)(f,c,a,h);var x;-1!=window.navigator.userAgent.indexOf("WebKit")&&(x=a.contentWindow.document,x.open(),l=x.createElement("div"),q={},t=h+"_inner",q.name=t,q.src="",q.style="display:none",(0,_.od)(f,l,q,t,g));
g=(0,_.Ja)(n.jb[0]);n.jb=[];l=(0,_.Ka)(n);n=f.createElement("form");n.action=l;n.method="POST";n.target=h;n.style.display="none";for(h=0;h<g.length;h++)l=f.createElement("input"),l.type="hidden",l.name=g[h][0],l.value=g[h][1],n.appendChild(l);c.appendChild(n);n.submit();n.parentNode.removeChild(n);x&&x.close();c=a}else c=(0,_.od)(f,c,a,h,g);return c};
_.sd={allowtransparency:"true",frameborder:"0",hspace:"0",marginheight:"0",marginwidth:"0",scrolling:"no",style:"",tabindex:"0",vspace:"0",width:"100%"};_.pd={allowtransparency:_.r,onload:_.r};_.rd=0;
_.td=function(a){_.S.Hg[a]||(_.S.Hg[a]={},_.R.N(a,function(c,f){var g=this.f;if("string"==typeof c&&!(c in{})&&!(g in{})){var h=this.callback,l=_.S.Hg[a][g],n;l&&window.Object.hasOwnProperty.call(l,c)?n=l[c]:window.Object.hasOwnProperty.call(_.S.Xd,a)&&(n=_.S.Xd[a]);if(n)return g=window.Array.prototype.slice.call(arguments,1),n._iframe_wrapped_rpc_&&h&&g.push(h),n.apply({},g)}(0,_.ua)(['Unregistered call in window "',window.name,'" for method "',a,'", via proxyId "',c,'" from frame "',g,'".'].join(""));
return _.s}));return _.S.Hg[a]};_.ud=function(a,c,f){function g(g){var l=window.Array.prototype.slice.call(arguments,0),n=l[l.length-1];if("function"===typeof n){var q=n;l.pop()}l.unshift(c,a,q,f);_.R.call.apply(_.R,l)}g._iframe_wrapped_rpc_=_.r;return g};_.vd=function(a,c){var f=(0,_.I)(_.Qa,"watt",(0,_.L)());(0,_.I)(f,a,c)};_.wd=function(a){var c=(0,_.Ga)(a.location.href,"urlindex");if(c=(0,_.I)(_.Qa,"fUrl",[])[c]){var f=a.location.hash,c=c+(/#/.test(c)?f.replace(/^#/,"&"):f);a.location.replace(c)}};
_.xd=function(){_.S.Xk++;return["I",_.S.Xk,"_",(new window.Date).getTime()].join("")};_.yd=function(a){if(0==a.indexOf("http:")||0==a.indexOf("https:")||0==a.indexOf("javascript:"))return a;if(0==a.indexOf("//"))return window.location.protocol+a;if(0==a.indexOf("/"))return window.location.protocol+"//"+window.location.host+a;var c=window.location.protocol+"//"+window.location.host+window.location.pathname,f=c.lastIndexOf("/");return c.substring(0,f+1)+a};
_.zd=function(a){return a instanceof window.Array?a.join(","):a instanceof window.Object?_.P.stringify(a):a};
_.Ad=function(a,c,f){var g={},h=a.indexOf("#");-1==h?(g.hash=_.s,g.uc=a):(g.hash=a.substring(h+1),g.uc=a.substring(0,h));a=g.uc.indexOf("?");-1==a?g.jb=_.s:(g.jb=g.uc.substring(a+1),g.uc=g.uc.substring(0,a));a=f?g.hash?[g.hash]:[]:g.jb?[g.jb]:[];for(var l in c)c.hasOwnProperty(l)&&(h=(0,_.zd)(c[l]),a.push([(0,_.Bd)(l),(0,_.Bd)(h)].join("=")));f?g.hash=a.join("&"):g.jb=a.join("&");return g.uc+(g.jb?"?"+g.jb:"")+(g.hash?"#"+g.hash:"")};
_.Cd=function(){var a=(0,_.kd)(_.p);return a!==_.p&&a!==_.s&&""!==a?"u/"+a+"/":""};_.Dd=function(a){a&&a.match(_.Ed)&&(0,_.bb)("googleapis.config/gcv",a)};_.Fd=function(a){_.Vc.fh.Tr(a)};_.Gd=function(a,c){var f=c||{},g;for(g in a)a.hasOwnProperty(g)&&(f[g]=a[g]);return f};
_.Hd=function(a,c,f,g,h){var l=[],n;for(n in a)if(a.hasOwnProperty(n)){var q=c,t=f,w=a[n],x=g,A=(0,_.td)(n);A[q]=A[q]||{};x=_.Q.ug(x,w);w._iframe_wrapped_rpc_&&(x._iframe_wrapped_rpc_=_.r);A[q][t]=x;l.push(n)}if(h)for(n in _.S.Xd)_.S.Xd.hasOwnProperty(n)&&l.push(n);return l.join(",")};_.Id=function(a,c,f){var g={};if(a&&a._methods){a=a._methods.split(",");for(var h=0;h<a.length;h++){var l=a[h];g[l]=(0,_.ud)(l,c,f)}}return g};
_.Jd=function(a){return a&&a.disableMultiLevelParentRelay?_.u:_.Yc&&_.Yc._open&&"inline"!=a.style&&a.inline!==_.r&&!(a.container&&("string"==typeof a.container&&window.document.getElementById(a.container)||window.document==(a.container.ownerDocument||a.container.document)))};_.Kd=function(a,c){function f(){}f.prototype=c.prototype;a.prototype=new f};
_.Ld=function(a,c,f,g,h,l,n,q){if(":"==a.charAt(0)){var t=(0,_.N)("iframes/"+a.substring(1));a={};(0,_.Ea)(t,a);if(t=a.url)t=t||"",t=t.replace(/:session_prefix:/g,(0,_.Cd)()),t=t.replace(/:session_index:/g,(0,_.kd)(_.p)||"0"),t=t.replace(/:socialhost:/g,(0,_.N)("iframes/:socialhost:")),a.url=(0,_.yd)(t);a.params||(a.params={})}else a={url:(0,_.yd)(a)};this.Da=a;this.openParams=this.va=c;this.Wa=f||{};this.Va=g;this.j=_.u;c=c.style;if(!this.j)if(c=c&&!_.S.qf[c]&&_.S.ph[c]){this.k=[];var w=this;c(function(){w.j=
_.r;for(var a=0,c=w.k.length;a<c;++a)w.k[a].call(w)})}else this.j=_.r;this.d={};(0,_.Md)(this,function(){var a;(a=this.va.style)&&_.S.qf[a]?a=_.S.qf[a]:a?((0,_.ub)(['Missing handler for style "',a,'". Continuing with default handler.'].join("")),a=_.s):a=_.Nd;if(a){var c;if("function"===typeof a)c=a(this);else{var f={};for(c in a){var g=a[c];f[c]="function"===typeof g?_.Q.ug(a,g,this):g}c=f}for(var n in h)a=c[n],"function"===typeof a&&(0,_.Od)(this,h[n],_.Q.ug(c,a))}l&&(0,_.Od)(this,"close",l)});
this.wa=this.ac=n;this.Ki=(q||[]).slice();n&&this.Ki.unshift(n.Z())};_.Md=function(a,c){a.j?c.call(a):a.k.push(c)};_.Od=function(a,c,f){a.d[c]=a.d[c]||[];a.d[c].push(f)};_.Pd=function(a,c){return"number"==typeof c?{value:c,ld:c+"px"}:"100%"==c?{value:100,ld:"100%",gl:_.r}:_.s};_.Qd=function(a){return(0,_.Ad)(a.Da.url,a.Wa,_.u)};
_.Rd=function(a,c,f,g,h,l,n){_.Ld.call(this,a,c,f,g,_.Sd,h,l,n);this.id=c.id||(0,_.xd)();this.i=c.rpcToken||window.Math.round(1E9*(0,_.ad)());a=this.Wa;c={};f=this.Da.params||{};for(var q in a)"#"==q.charAt(0)&&(c[q.substring(1)]=a[q]),0==q.indexOf("fr-")&&(c[q.substring(3)]=a[q]),"#"==f[q]&&(c[q]=a[q]);for(var t in c)delete a["fr-"+t],delete a["#"+t],delete a[t];this.Y=c;this.o={};(0,_.Md)(this,function(){this.Nb("open");(0,_.Gd)(this.o,this)})};
_.Td=function(a,c,f,g,h,l,n){_.Ld.call(this,a,c,f,g,_.Ud,h,l,n);this.url=a;this.b=_.s;this.z=(0,_.xd)();(0,_.Md)(this,function(){this.Nb("beforeparentopen");var a=(0,_.Gd)(this.Va);a._onopen=this.ea;a._ready=this.Bg;a._onclose=this.H;this.Wa._methods=(0,_.Hd)(a,"..",this.z,this,_.r);var a={},c;for(c in this.Wa)a[c]=(0,_.zd)(this.Wa[c]);var f=this.Da.url;if(this.va.hideUrlFromParent){c=window.name;var g=f,f=(0,_.Qd)(this),h=a,a={};a._methods=h._methods;a["#opener"]=h["#opener"];a["#urlindex"]=h["#urlindex"];
a["#opener"]&&h["#urlindex"]!=_.p?(a["#opener"]=c+","+a["#opener"],c={url:g,Wa:a}):(g=(0,_.I)(_.Qa,"fUrl",[]),h=g.length,g[h]=f,_.Qa.rUrl=_.wd,a["#opener"]=c,a["#urlindex"]=h,c=_.Vc.ja(_.eb.location.href),f=(0,_.N)("iframes/relay_url_"+(0,window.encodeURIComponent)(c))||"/_/gapi/sibling/1/frame.html",c={url:c+f,Wa:a});f=c.url;a=c.Wa}_.Yc._open({url:f,openParams:this.va,params:a,proxyId:this.z,openedByProxyChain:this.Ki})})};
_.Vd=function(a,c,f,g,h,l,n){_.Ld.call(this,a,c,f,g,_.Ud,l,n);this.id=c.id||(0,_.xd)();this.i=h;g._close=this.close;this.onClosed=this.b;this.C=0;(0,_.Md)(this,function(){this.Nb("beforeparentopen");var a=(0,_.Gd)(this.Va);this.Wa._methods=(0,_.Hd)(a,"..",this.z,this,_.r);var a=(0,_.Ad)(this.Da.url,this.Wa,_.u),a=_.Wd.Qu(_.fb,a,this.id,{}),c=h.El(a);this.canAutoClose=function(a){a(h.Oj(c))};h.dm(c,this);this.C=c})};_.Xd=function(a){return _.S.qf[a]};_.Yd=function(a,c){_.S.qf[a]=c}; _.Zd=function(a){a=a||{};"auto"===a.height&&(a.height=_.zb.Hh());var c=window&&_.$d&&_.$d.ma();c?c.Sl(a.width||0,a.height||0):_.Yc&&_.Yc._resizeMe&&_.Yc._resizeMe(a)};_.ae=function(a){(0,_.Dd)(a)};_.Wd={};
_.S.K=_.S.K||{};_.S.K.zo=function(a){try{return!!a.document}catch(c){}return _.u};_.S.K.lk=function(a){var c=a.parent;return a!=c&&_.S.K.zo(c)?_.S.K.lk(c):a};_.S.K.Tu=function(a){var c=a.userAgent||"";a=a.product||"";return 0!=c.indexOf("Opera")&&-1==c.indexOf("WebKit")&&"Gecko"==a&&0<c.indexOf("rv:1.")};
if(window.ToolbarApi)_.$d=window.ToolbarApi,_.$d.ma=window.ToolbarApi.getInstance,_.$d.prototype=window.ToolbarApi.prototype,_.B=_.$d.prototype,_.B.El=_.$d.prototype.openWindow,_.B.Qj=_.$d.prototype.closeWindow,_.B.dm=_.$d.prototype.setOnCloseHandler,_.B.Oj=_.$d.prototype.canClosePopup,_.B.Sl=_.$d.prototype.resizeWindow;else{_.be=_.s;_.$d=(0,_.v)();_.$d.ma=function(){!_.be&&(window.external&&window.external.GTB_IsToolbar)&&(_.be=new _.$d);return _.be};_.B=_.$d.prototype;_.B.El=function(a){return window.external.GTB_OpenPopup&&
window.external.GTB_OpenPopup(a)};_.B.Qj=function(a){window.external.GTB_ClosePopupWindow&&window.external.GTB_ClosePopupWindow(a)};_.B.dm=function(a,c){window.external.GTB_SetOnCloseHandler&&window.external.GTB_SetOnCloseHandler(a,c)};_.B.Oj=function(a){return window.external.GTB_CanClosePopup&&window.external.GTB_CanClosePopup(a)};_.B.Sl=function(a,c){return window.external.GTB_ResizeWindow&&window.external.GTB_ResizeWindow(a,c)};window.ToolbarApi=_.$d;window.ToolbarApi.getInstance=_.$d.ma};
_.Ed=/^[-_.0-9A-Za-z]+$/;_.Sd={open:"open",onready:"ready",close:"close",onresize:"resize",onOpen:"open",onReady:"ready",onClose:"close",onResize:"resize",onRenderStart:"renderstart"};_.Ud={onBeforeParentOpen:"beforeparentopen"};_.Nd={onOpen:function(a){var c=a.va;a.Ma(c.container||c.element);return a},onClose:function(a){a.remove()}};_.Bd=window.encodeURIComponent||window.escape;_.S.kp=function(a){var c=(0,_.L)();(0,_.Ea)(_.sd,c);(0,_.Ea)(a,c);return c};_.B=_.Ld.prototype;_.B.Jh=(0,_.y)("va");
_.B.Ib=(0,_.y)("Wa");_.B.Ih=(0,_.y)("Va");_.B.Kh=(0,_.y)("wa");_.B.ha=function(a,c){(0,_.Md)(this,function(){(0,_.Od)(this,a,c)})};_.B.Ic=function(a,c){(0,_.Md)(this,function(){var f=this.d[a];if(f)for(var g=0,h=f.length;g<h;++g)if(f[g]===c){f.splice(g,1);break}})};
_.B.Nb=function(a,c){var f,g=this.d[a];if(g)for(var h=window.Array.prototype.slice.call(arguments,1),l=0,n=g.length;l<n;++l)try{f=g[l].apply({},h)}catch(q){(0,_.ua)(['Exception when calling callback "',a,'" with exception "',q.name,": ",q.message,'".'].join(""))}return f};(0,_.Kd)(_.Rd,_.Ld);_.B=_.Rd.prototype;
_.B.Ma=function(a,c){if(!this.Da.url)return(0,_.ua)("Cannot open iframe, empty URL."),this;var f=this.id;_.S.Qc[f]=this;var g=(0,_.Gd)(this.Va);g._ready=this.Bg;g._close=this.close;g._open=this.Fl;g._resizeMe=this.Tl;g._renderstart=this.Bl;var h=this.Y;this.i&&(h.rpctoken=this.i);h._methods=(0,_.Hd)(g,f,"",this,_.r);g=(0,_.Qd)(this);(0,_.Ad)(g,h,_.r);this.T=a="string"===typeof a?window.document.getElementById(a):a;g=(0,_.Qd)(this);g=(0,_.Ad)(g,h,_.r);h={id:f};if(c){h.attributes=c;var l=c.style;if("string"===
typeof l){var n;if(l){n=[];for(var l=l.split(";"),q=0,t=l.length;q<t;++q){var w=l[q];0==w.length&&q+1==t||(w=w.split(":"),2==w.length&&w[0].match(/^[ a-zA-Z_-]+$/)&&w[1].match(/^[ +.%0-9a-zA-Z_-]+$/)?n.push(w.join(":")):(0,_.ua)(['Iframe style "',l[q],'" not allowed.'].join("")))}n=n.join(";")}else n="";c.style=n}}this.va.allowPost&&(h.allowPost=_.r);this.b=(0,_.qd)(g,a,h);_.S.Qc[f]=this;f=g;_.R.Lg(this.id,this.i);_.R.Mg(this.id,f);return this};_.B.Ia=function(a,c){this.o[a]=c};_.B.Z=(0,_.y)("id");
_.B.aa=(0,_.y)("b");_.B.Cp=(0,_.y)("T");_.B.Kc=(0,_.ba)("T");_.B.Bg=function(a){var c=(0,_.Id)(a,this.id,"");this.wa&&"function"==typeof this.Va._ready&&(a._methods=(0,_.Hd)(c,this.wa.Z(),this.id,this,_.u),this.Va._ready(a));(0,_.Gd)(a,this);(0,_.Gd)(c,this);this.Nb("ready",a)};_.B.Bl=function(a){this.Nb("renderstart",a)};_.B.close=function(a){a=this.Nb("close",a);delete _.S.Qc[this.id];return a};_.B.remove=function(){var a=window.document.getElementById(this.id);a&&a.parentNode&&a.parentNode.removeChild(a)};
_.B.Fl=function(a){var c=(0,_.Id)(a.params,this.id,a.proxyId);delete a.params._methods;"_parent"==a.openParams.anchor&&(a.openParams.anchor=this.T);if((0,_.Jd)(a.openParams))new _.Td(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain);else{var f=new _.Rd(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain),g=this;(0,_.Md)(f,function(){var a={childId:f.Z()},l=f.o;l._toclose=f.close;a._methods=(0,_.Hd)(l,g.id,f.id,f,_.u);c._onopen(a)})}};
_.B.Tl=function(a){if(this.Nb("resize",a)===_.p&&this.b){var c=(0,_.Pd)(this,a.width);c!=_.s&&(this.b.style.width=c.ld);a=(0,_.Pd)(this,a.height);a!=_.s&&(this.b.style.height=a.ld);if(this.b.parentElement&&(c!=_.s&&c.gl||a!=_.s&&a.gl))this.b.parentElement.style.display="block"}};(0,_.Kd)(_.Td,_.Ld);_.Td.prototype.i=(0,_.y)("b");
_.Td.prototype.ea=function(a){this.b=a.childId;var c=(0,_.Id)(a,"..",this.b);(0,_.Gd)(c,this);this.close=c._toclose;_.S.Qc[this.b]=this;this.wa&&this.Va._onopen&&(a._methods=(0,_.Hd)(c,this.wa.Z(),this.b,this,_.u),this.Va._onopen(a))};_.Td.prototype.Bg=function(a){var c=(0,window.String)(this.b),f=(0,_.Id)(a,"..",c);(0,_.Gd)(a,this);(0,_.Gd)(f,this);this.Nb("ready",a);this.wa&&this.Va._ready&&(a._methods=(0,_.Hd)(f,this.wa.Z(),c,this,_.u),this.Va._ready(a))};
_.Td.prototype.H=function(a){if(this.wa&&this.Va._onclose)this.Va._onclose(a);else return a=this.Nb("close",a),delete _.S.Qc[this.b],a};(0,_.Kd)(_.Vd,_.Ld);_.Vd.prototype.close=function(a){a=this.Nb("close",a);this.i.Qj(this.C);return a};_.Vd.prototype.b=function(){this.Nb("close")};_.S.Qc={};_.S.qf={};_.S.ph={};_.S.Xk=0;_.S.Hg={};_.S.Xd={};_.S.Eg=_.s;_.S.Dg=[];
_.S.dr=function(a){var c=_.u;try{if(a!=_.s)var f=window.parent.frames[a.id],c=f.iframer.id==a.id&&f.iframes.openedId_(_.Yc.id)}catch(g){}try{_.S.Eg={origin:this.origin,referer:this.referer,claimedOpenerId:a&&a.id,claimedOpenerProxyChain:a&&a.proxyChain||[],sameOrigin:c};for(a=0;a<_.S.Dg.length;++a)_.S.Dg[a](_.S.Eg);_.S.Dg=[]}catch(h){}};_.S.up=function(a){var c=a&&a.wa,f=_.s;c&&(f={},f.id=c.Z(),f.proxyChain=a.Ki);return f};_.R.N("_noop_echo",function(){this.callback(_.S.up(_.S.Qc[this.f]))});
if(window.parent!=window){_.ce=_.Q.na();_.ce.gcv&&(0,_.Dd)(_.ce.gcv);_.de=_.ce.jsh;_.de&&(0,_.Fd)(_.de);(0,_.Gd)((0,_.Id)(_.ce,"..",""),_.Yc);(0,_.Gd)(_.ce,_.Yc);window.setTimeout(function(){_.R.call("..","_noop_echo",_.S.dr)},0)}_.S.qa=_.Xd;_.S.la=_.Yd;_.S.Rr=_.ae;_.S.Wc=_.Zd;_.S.ep=function(a){return _.S.ph[a]};_.S.Wi=function(a,c){_.S.ph[a]=c};_.S.wr=_.Zd;_.S.Yr=_.ae;_.S.gg={};_.S.gg.get=_.Xd;_.S.gg.set=_.Yd;_.S.oo=function(a,c){(0,_.td)(a);_.S.Xd[a]=c||window[a]};_.S.Nu=function(a){delete _.S.Xd[a]};
_.S.open=function(a,c,f,g,h,l){3==arguments.length?g={}:4==arguments.length&&"function"===typeof g&&(h=g,g={});var n="bubble"===c.style&&_.$d&&_.$d.ma();return n?new _.Vd(a,c,f,g,n,h,l):(0,_.Jd)(c)?new _.Td(a,c,f,g,h,l):new _.Rd(a,c,f,g,h,l)};_.S.close=function(a,c){_.Yc&&_.Yc._close&&_.Yc._close(a,c)};
_.S.Rb=function(a,c,f){2==arguments.length&&"function"===typeof h&&(f=c,c={});var g=a||{};"height"in g||(g.height=_.zb.Hh());var h=c||{};g._methods=(0,_.Hd)(h,"..","",_.Yc,_.r);_.Yc&&_.Yc._ready&&_.Yc._ready(g,f)};_.S.gk=function(a){_.S.Eg?a(_.S.Eg):_.S.Dg.push(a)};_.S.$q=function(a){return!!_.S.Qc[a]};_.S.ip=function(){return["https://ssl.gstatic.com/gb/js/",(0,_.N)("googleapis.config/gcv")].join("")};
_.S.ir=function(a){var c={mouseover:1,mouseout:1};if(_.Yc._event)for(var f=0;f<a.length;f++){var g=a[f];g in c&&_.Q.ye(window.document,g,function(a){_.Yc._event({event:a.type,timestamp:(new window.Date).getTime()})},_.r)}};_.S.Ur=_.Fd;_.S.Vi=function(a){_.Vc.fh.Vi(a)};_.S.av=(0,_.v)();_.S.xq=_.Yc;
(0,_.O)("iframes.allow",_.S.oo);(0,_.O)("iframes.callSiblingOpener",_.S.yo);(0,_.O)("iframes.registerForOpenedSibling",_.S.jr);(0,_.O)("iframes.close",_.S.close);(0,_.O)("iframes.getGoogleConnectJsUri",_.S.ip);(0,_.O)("iframes.getHandler",_.S.qa);(0,_.O)("iframes.getDeferredHandler",_.S.ep);(0,_.O)("iframes.getParentInfo",_.S.gk);(0,_.O)("iframes.iframer",_.S.xq);(0,_.O)("iframes.open",_.S.open);(0,_.O)("iframes.openedId_",_.S.$q);(0,_.O)("iframes.propagate",_.S.ir);(0,_.O)("iframes.ready",_.S.Rb);
(0,_.O)("iframes.resize",_.S.Wc);(0,_.O)("iframes.setGoogleConnectJsVersion",_.S.Rr);(0,_.O)("iframes.setBootstrapHint",_.S.Vi);(0,_.O)("iframes.setJsHint",_.S.Ur);(0,_.O)("iframes.setHandler",_.S.la);(0,_.O)("iframes.setDeferredHandler",_.S.Wi);(0,_.O)("IframeBase",_.Ld);(0,_.O)("IframeBase.prototype.addCallback",_.Ld.prototype.ha);(0,_.O)("IframeBase.prototype.getMethods",_.Ld.prototype.Ih);(0,_.O)("IframeBase.prototype.getOpenerIframe",_.Ld.prototype.Kh);
(0,_.O)("IframeBase.prototype.getOpenParams",_.Ld.prototype.Jh);(0,_.O)("IframeBase.prototype.getParams",_.Ld.prototype.Ib);(0,_.O)("IframeBase.prototype.removeCallback",_.Ld.prototype.Ic);(0,_.O)("Iframe",_.Rd);(0,_.O)("Iframe.prototype.close",_.Rd.prototype.close);(0,_.O)("Iframe.prototype.exposeMethod",_.Rd.prototype.Ia);(0,_.O)("Iframe.prototype.getId",_.Rd.prototype.Z);(0,_.O)("Iframe.prototype.getIframeEl",_.Rd.prototype.aa);(0,_.O)("Iframe.prototype.getSiteEl",_.Rd.prototype.Cp);
(0,_.O)("Iframe.prototype.openInto",_.Rd.prototype.Ma);(0,_.O)("Iframe.prototype.remove",_.Rd.prototype.remove);(0,_.O)("Iframe.prototype.setSiteEl",_.Rd.prototype.Kc);(0,_.O)("Iframe.prototype.addCallback",_.Rd.prototype.ha);(0,_.O)("Iframe.prototype.getMethods",_.Rd.prototype.Ih);(0,_.O)("Iframe.prototype.getOpenerIframe",_.Rd.prototype.Kh);(0,_.O)("Iframe.prototype.getOpenParams",_.Rd.prototype.Jh);(0,_.O)("Iframe.prototype.getParams",_.Rd.prototype.Ib);
(0,_.O)("Iframe.prototype.removeCallback",_.Rd.prototype.Ic);(0,_.O)("IframeProxy",_.Td);(0,_.O)("IframeProxy.prototype.getTargetIframeId",_.Td.prototype.i);(0,_.O)("IframeProxy.prototype.addCallback",_.Td.prototype.ha);(0,_.O)("IframeProxy.prototype.getMethods",_.Td.prototype.Ih);(0,_.O)("IframeProxy.prototype.getOpenerIframe",_.Td.prototype.Kh);(0,_.O)("IframeProxy.prototype.getOpenParams",_.Td.prototype.Jh);(0,_.O)("IframeProxy.prototype.getParams",_.Td.prototype.Ib);
(0,_.O)("IframeProxy.prototype.removeCallback",_.Td.prototype.Ic);(0,_.O)("IframeWindow",_.Vd);(0,_.O)("IframeWindow.prototype.close",_.Vd.prototype.close);(0,_.O)("IframeWindow.prototype.onClosed",_.Vd.prototype.b);(0,_.O)("iframes.util.getTopMostAccessibleWindow",_.S.K.lk);(0,_.O)("iframes.handlers.get",_.S.gg.get);(0,_.O)("iframes.handlers.set",_.S.gg.set);(0,_.O)("iframes.resizeMe",_.S.wr);(0,_.O)("iframes.setVersionOverride",_.S.Yr);

_.ee=function(a){var c=(0,_.Ta)();return c?c(a):_.u};_.fe=(0,_.I)(_.Qa,"rw",(0,_.L)());
_.ge=function(a,c){var f=_.fe[a];f&&f.state<c&&(f.state=c)};_.he=function(a){a=(a=_.fe[a])?a.oid:_.p;if(a){var c=_.fb.getElementById(a);c&&c.parentNode.removeChild(c);delete _.fe[a];(0,_.he)(a)}};_.ie=function(a){a=a.style;a.textIndent="0";a.margin="0";a.padding="0";a.background="transparent";a.borderStyle="none";a.cssFloat="none";a.styleFloat="none";a.lineHeight="normal";a.fontSize="1px";a.verticalAlign="baseline"};
_.ke=function(a){a=a.va.container;"string"===typeof a&&(a=window.document.getElementById(a));return a};_.le=function(a){var c=a.clientWidth;return"position:absolute;top:-10000px;width:"+(c?c+"px":a.style.width||"300px")+";margin:0px;border-style:none;"};
_.me=function(a,c){var f={};f.width=c?c.width:a.width;f.height=c?c.height:a.height;var g=a.aa(),h=a.Z();(0,_.ge)(h,2);(h=_.fe[h])&&(h.args=f);a:{h=g.parentNode;f=f||{};if((0,_.ee)()){if("number"===typeof _.Qa.ucs)break a;var l=g.id;if(l){var n;n=(n=_.fe[l])?n.state:_.p;if(1===n||4===n)break a;(0,_.he)(l)}}n=f.width;f=f.height;(0,_.ie)(h);h.style.display="inline-block";g=g.style;g.position="static";g.left=0;g.top=0;g.visibility="visible";n&&(g.width=n+"px");f&&(g.height=f+"px");l&&(0,_.ge)(l,3)}(l= c?c.title:_.s)&&a.aa().setAttribute("title",l)};
_.ne={open:function(a){var c=(0,_.ke)(a);return a.Ma(c,{style:(0,_.le)(c,a)})},attach:function(a,c){var f=(0,_.ke)(a),g=c.id,h=c.getAttribute("data-postorigin")||c.src,l=/#(?:.*&)?rpctoken=(\d+)/.exec(h),l=l&&l[1];a.id=g;a.i=l;a.T=c.parentNode;a.b=c;_.S.Qc[g]=a;l=(0,_.Gd)(a.Va);l._ready=a.Bg;l._close=a.close;l._open=a.Fl;l._resizeMe=a.Tl;l._renderstart=a.Bl;(0,_.Hd)(l,g,"",a,_.r);_.R.Lg(a.id,a.i);_.R.Mg(a.id,h);var f=_.S.kp({style:(0,_.le)(f,a)}),n;for(n in f)window.Object.prototype.hasOwnProperty.call(f, n)&&("style"==n?a.b.style.cssText=f[n]:a.b.setAttribute(n,f[n]))}};_.ne.onready=_.me;_.ne.onRenderStart=_.me;_.ne.close=function(a){var c=a.T;c&&c.removeChild(a.aa())};_.S.la("inline",_.ne);


_.oe=function(a){var c;a.match(/^https?%3A/i)&&(c=(0,window.decodeURIComponent)(a));a=c?c:a;return(0,_.Na)(window.document,a)};_.pe=function(a){a=a||"canonical";for(var c=window.document.getElementsByTagName("link"),f=0,g=c.length;f<g;f++){var h=c[f],l=h.getAttribute("rel");if(l&&l.toLowerCase()==a&&(h=h.getAttribute("href")))return(0,_.oe)(h)}return window.location.href};_.qe=function(a,c,f,g){return(a="string"==typeof a?a:_.p)?(0,_.oe)(a):(0,_.pe)(g)};
_.re=function(a){return"string"==typeof a?""!=a&&"0"!=a&&"false"!=a.toLowerCase():!!a};_.se=function(a){var c=(0,window.parseInt)(a,10);if(c==a)return(0,window.String)(c)};_.te=function(a){if((0,_.re)(a))return"true"};_.ue=function(a){return"string"==typeof a&&_.ve[a.toLowerCase()]?a.toLowerCase():"standard"};_.we=function(a,c){return"tall"==(0,_.ue)(c)?"true":a==_.s||(0,_.re)(a)?"true":"false"};_.xe=function(a,c,f){a==_.s&&f&&(a=f.db,a==_.s&&(a=f.gwidget&&f.gwidget.db));return a||_.p};
_.ye=function(a,c,f){a==_.s&&f&&(a=f.ecp,a==_.s&&(a=f.gwidget&&f.gwidget.ecp));return a||_.p};_.ve={tall:{"true":{width:50,height:60},"false":{width:50,height:24}},small:{"false":{width:24,height:15},"true":{width:70,height:15}},medium:{"false":{width:32,height:20},"true":{width:90,height:20}},standard:{"false":{width:38,height:24},"true":{width:106,height:24}}};
_.ze={href:[_.qe,"url"],width:[_.se],size:[_.ue],resize:[_.te],autosize:[_.te],count:[function(a,c){return(0,_.we)(c.count,c.size)}],db:[_.xe],ecp:[_.ye],textcolor:[function(a){if("string"==typeof a&&a.match(/^[0-9A-F]{6}$/i))return a}],drm:[_.te],recommendations:[],fu:[],ad:[_.te],cr:[_.se],ag:[_.se],"fr-ai":[],"fr-sigh":[]};


_.Ae=(0,_.Sa)();
_.Be=function(a,c){if(!_.Ce){var f=(0,_.N)("iframes/:socialhost:"),g=(0,_.kd)(_.p)||"0",h=(0,_.kd)(_.p);_.Ce={socialhost:f,session_index:g,session_prefix:h!==_.p&&h!==_.s&&""!==h?"u/"+h+"/":"",im_prefix:(0,_.N)("googleapis.config/signedIn")===_.u?"_/im/":""}}return _.Ce[c]||""};_.De=function(a,c,f){return(0,_.qe)(a,c,f,c.action?_.p:"publisher")};_.Ee=function(){return window.location.origin||window.location.protocol+"//"+window.location.host};
_.Fe=function(a){var c=_.p;"number"===typeof a?c=a:"string"===typeof a&&(c=(0,window.parseInt)(a,10));return c};_.Ge=function(a,c){if("string"==typeof a){a=a.toLowerCase();var f;for(f=0;f<c.length;f++)if(c[f]==a)return a}};_.He=function(a){return(0,_.Ge)(a,_.Ie)};_.Je=function(a){return(0,_.Ge)(a,_.Ke)};_.Le=function(a){a.source=[_.s,"source"];a.expandTo=[_.s,"expandTo"];a.align=[_.Je];a.annotation=[_.He];a.origin=[_.Ee]};
_.Me=function(a){if(_.Ca.test(window.Object.keys))return window.Object.keys(a);var c=[],f;for(f in a)(0,_.Da)(a,f)&&c.push(f);return c};
_.Ne=function(a,c){_.Oe.ps0=(new window.Date).getTime();(0,_.Pe)("ps0");var f=("string"===typeof a?window.document.getElementById(a):a)||_.fb,g;g=_.fb.documentMode;if(f.querySelectorAll&&(!g||8<g)){g=c?[c]:(0,_.Me)(_.Qe).concat((0,_.Me)(_.Re)).concat((0,_.Me)(_.Se));for(var h=[],l=0;l<g.length;l++){var n=g[l];h.push(".g-"+n,"g\\:"+n)}g=f.querySelectorAll(h.join(","))}else g=f.getElementsByTagName("*");f=(0,_.L)();for(h=0;h<g.length;h++){l=g[h];var q=l,n=c,t=q.nodeName.toLowerCase(),w=_.p;q.getAttribute("data-gapiscan")?
n=_.s:(0==t.indexOf("g:")?w=t.substr(2):(q=(q=(0,window.String)(q.className||q.getAttribute("class")))&&_.Te.exec(q))&&(w=q[1]),n=w&&(_.Qe[w]||_.Re[w]||_.Se[w])&&(!n||w===n)?w:_.s);n&&(l.setAttribute("data-gapiscan",_.r),(0,_.I)(f,n,[]).push(l))}for(var x in f)_.Ue.push(x);_.Oe.ps1=(new window.Date).getTime();(0,_.Pe)("ps1");(x=_.Ue.join(":"))&&_.gb.load(x,_.p);var A,l=[];for(A in f){h=f[A];g=0;for(x=h.length;g<x;g++){for(var q=h[g],n=A,t=w=q,q=(0,_.L)(),E=0!=t.nodeName.toLowerCase().indexOf("g:"),
J=0,K=t.attributes.length;J<K;J++){var M=t.attributes[J],V=M.name,M=M.value;0<=_.xb.call(_.Ve,V)||(E&&0!=V.indexOf("data-")||"null"===M)||(E&&(V=V.substr(5)),q[V.toLowerCase()]=M)}t=t.style;(E=(0,_.Fe)(t&&t.height))&&(q.height=(0,window.String)(E));(t=(0,_.Fe)(t&&t.width))&&(q.width=(0,window.String)(t));(0,_.We)(n,w,q,l,x)}}};
_.Xe=function(a,c){var f=(0,_.I)(_.Qa,"watt",(0,_.L)())[a];c&&f?(f(c),(f=c.iframeNode)&&f.setAttribute("data-gapiattached",_.r)):_.gb.load(a,function(){var f=(0,_.I)(_.Qa,"watt",(0,_.L)())[a],h=c&&c.iframeNode;!h||!f?(0,_.gb[a].go)(h&&h.parentNode):(f(c),h.setAttribute("data-gapiattached",_.r))})};
_.We=function(a,c,f,g,h){switch((0,_.Ye)(c,a)){case 0:case 1:g={};g.iframeNode=c;g.userParams=f;(0,_.Xe)(a,g);break;case 2:if(c.parentNode){var l=_.r;f.dontclear&&(l=_.u);delete f.dontclear;var n;var q;c:{var t=a,w=a;"plus"==a&&f.action&&(t=a+"_"+f.action,w=a+"/"+f.action);q=(0,_.N)("iframes/"+t+"/url");if(!q){if((0,_.I)(_.Qa,"SM",(0,_.L)())[t]){q=_.s;break c}q=":socialhost:/_/widget/render/"+w}q=q.replace(_.Ze,_.Be)}if(q){t={};(0,_.Ea)(f,t);t.hl=(0,_.N)("lang")||"en-US";t.origin=(0,_.Ee)();t.exp=
(0,_.N)("iframes/"+a+"/params/exp");if(w=(0,_.N)("iframes/"+a+"/params/location"))for(var x=0;x<w.length;x++){var A=w[x];t[A]=_.eb.location[A]}switch(a){case "plus":t.url=(0,_.De)(t.href,f,_.s);delete t.href;break;case "plusone":case "recobox":t.url=f.href?(0,_.oe)(f.href):(0,_.pe)();t.db=(0,_.xe)(f.db,_.p,(0,_.N)());t.ecp=(0,_.ye)(f.ecp,_.p,(0,_.N)());delete t.href;break;case "signin":t.url=(0,_.pe)()}t.hl=(0,_.N)("lang")||"en-US";_.Qa.ILI&&(t.iloader="1");delete t["data-onload"];delete t.rd;w=(0,_.N)("inline/css");
"undefined"!==typeof w&&(0<h&&w>=h)&&(t.ic="1");w=/^#|^fr-/;h={};for(var E in t)(0,_.Da)(t,E)&&w.test(E)&&(h[E.replace(w,"")]=t[E],delete t[E]);E=[].concat(_.$e);w=(0,_.N)("iframes/"+a+"/methods");"object"===typeof w&&_.Ca.test(w.push)&&(E=E.concat(w));for(n in f)if((0,_.Da)(f,n)&&/^on/.test(n)&&("plus"!=a||"onconnect"!=n))E.push(n),delete t[n];delete t.callback;h._methods=E.join(",");n=(0,_.Ma)(q,t,h)}else n=_.s;n?(f.rd?E=c:(E=window.document.createElement("div"),c.setAttribute("data-gapistub",_.r),
E.style.cssText="position:absolute;width:100px;left:-10000px;",c.parentNode.insertBefore(E,c)),E.id||(c=E,(0,_.I)(_.Ae,a,0),q="___"+a+"_"+_.Ae[a]++,c.id=q),c=(0,_.L)(),c[">type"]=a,(0,_.Ea)(f,c),E.setAttribute("data-gwattr",(0,_.La)(c).join(":")),c=E,E={allowPost:1,attributes:_.af},E.dontclear=!l,c=(0,_.qd)(n,c,E),l={},l.userParams=f,l.url=n,l.type=a,l.iframeNode=c,l.id=c.getAttribute("id"),f=l.id,c=(0,_.L)(),c.id=f,c.userParams=l.userParams,c.url=l.url,c.type=l.type,c.state=1,_.fe[f]=c,f=l):f=_.s}else f=
_.s;f&&((l=f.id)&&g.push(l),(0,_.Xe)(a,f))}};_.Ye=function(a,c){if(a&&1===a.nodeType&&c){if(_.Re[c])return 1;var f;if(f=_.Se[c])if(f=!!_.bf[a.nodeName.toLowerCase()])f=(f=a.innerHTML)&&f.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")?_.r:_.u;if(f)return 0;if(_.Qe[c])return 2}return _.s};_.cf=function(a,c,f,g){_.df[f]=_.df[f]||!!g;(0,_.I)(_.ef,f,[]);_.ef[f].push([a,c])};_.Pe=function(a,c,f){var g=_.ff.r;"function"===typeof g?g(a,c,f):g.push([a,c,f])};
_.gf=function(a,c,f,g){"_p"==c&&(0,_.m)((0,window.Error)("m`_p"));(0,_.hf)(c,f)[a]=g||(new window.Date).getTime();(0,_.Pe)(a,c,f)};_.hf=function(a,c){var f=(0,_.I)(_.jf,a,(0,_.L)());return(0,_.I)(f,c,(0,_.L)())};_.kf=function(a,c,f){var g=_.s;c&&f&&(g=(0,_.hf)(c,f)[a]);return g||_.Oe[a]};_.lf=function(a){this.t={};this.tick=function(a,f,g){this.t[a]=[g!=_.p?g:(new window.Date).getTime(),f]};this.tick("start",_.s,a)};_.mf=function(a,c){this.type=!a?"g":"_p"==a?"m":"w";this.name=a;this.b=c};
_.nf=function(a){var c=[];c.push("l"+((0,_.N)("isPlusUser")?"1":"0"));var f="m"+(_.of?"1":"0");c.push(f);if("m"==a.type)c.push("p"+a.b);else if("w"==a.type){var g="n"+a.b;c.push(g);"0"==a.b&&c.push(f+g)}return c};_.pf=function(a,c,f){for(var g=new _.mf(c,f),h=(0,_.I)(_.qf,g.key(),(0,_.L)()),l=_.ef[a]||[],n=0;n<l.length;++n){var q=l[n],t=h,w=q[0],x=a,A=c,E=f,q=(0,_.kf)(q[1],A,E),x=(0,_.kf)(x,A,E);t[w]=q&&x?x-q:_.s}_.df[a]&&_.rf&&((0,_.sf)(_.tf),(0,_.sf)(g))};
_.uf=function(a,c){c=c||[];for(var f=[],g=0;g<c.length;g++)f.push(a+c[g]);return f};
_.sf=function(a){var c=_.eb.__gapi_jstiming__;c.sn=_.vf[a.type];var f=new c.Timer(0),g;a:{switch(a.type){case "g":g="global";break a;case "m":g=a.b;break a;case "w":g=a.name;break a}g=_.p}f.name=g;g=_.u;var h=a.key(),l=_.qf[h];f.tick("_start",_.s,0);for(var n in l)f.tick(n,"_start",l[n]),g=_.r;_.qf[h]=(0,_.L)();if(g){n=[];g=(0,_.N)("lexps");n=n.concat((0,_.uf)("e",g));n=n.concat((0,_.uf)("",(0,_.nf)(a)));for(h=0;h<_.wf.length;h++)l=_.wf[h],0<=_.xb.call(g,l)&&(n=n.concat((0,_.uf)(l?"e"+l:"",(0,_.nf)(a))));
n=(0,_.uf)("abc_",n);c.report(f,{e:n.join(",")})}};_.xf=function(a){var c=(0,_.N)(a);return"undefined"!==typeof c?c:(0,_.N)("gwidget/"+a)};_.yf=function(a){return function(c){var f=a;"number"===typeof c?f=c:"string"===typeof c&&(f=c.indexOf("px"),-1!=f&&(c=c.substring(0,f)),f=(0,window.parseInt)(c,10));return f}};_.zf=function(a){"string"===typeof a&&(a=window[a]);return"function"===typeof a?a:_.s};_.Af=function(a,c,f,g){return _.S.open(a,c,f,g)};
_.Bf=function(a,c){for(var f in _.Cf)if(_.Cf.hasOwnProperty(f)){var g=_.Cf[f][1];g&&!c.hasOwnProperty(g)&&(c[g]=a[g])}return c};_.Df=function(a,c){var f={},g;for(g in a)a.hasOwnProperty(g)&&(f[a[g][1]||g]=(a[g]&&a[g][0]||_.Ef)(c[g],c,_.Ff));return f};_.Ef=function(a){return a};_.Gf=function(){};_.Ce=_.s;_.Ze=/:([a-zA-Z_]+):/g;_.$e="onPlusOne _ready _close,_open _resizeMe _renderstart oncircled".split(" ");_.Ie="inline bubble none only pp vertical-bubble".split(" ");_.Ke=["left","right"];
_.Ve=["style","data-gapiscan"];_.af={style:"position:absolute;top:-10000px;width:300px;margin:0px;borderStyle:none"};_.Te=/(?:^|\s)g-((\S)*)(?:$|\s)/;_.bf={button:_.r,div:_.r,span:_.r};_.Qe=(0,_.I)(_.Qa,"SW",(0,_.L)());_.Re=(0,_.I)(_.Qa,"SA",(0,_.L)());_.Se=(0,_.I)(_.Qa,"SM",(0,_.L)());_.Ue=(0,_.I)(_.Qa,"FW",[]);
(0,_.I)(_.gb,"platform",{}).go=_.Ne;_.ff=(0,_.I)(_.Qa,"perf",(0,_.L)());_.Oe=(0,_.I)(_.ff,"g",(0,_.L)());_.jf=(0,_.I)(_.ff,"i",(0,_.L)());(0,_.I)(_.ff,"r",[]);_.df=(0,_.L)();_.ef=(0,_.L)();_.Hf=new _.lf;window.__gapi_jstiming__={Timer:_.lf,load:_.Hf};if(window.performance&&window.performance.timing){_.If=window.performance.timing;_.Jf=window.__gapi_jstiming__.load;_.Kf=_.If.navigationStart;_.Lf=_.If.responseStart;0<_.Kf&&_.Lf>=_.Kf&&(_.Jf.tick("_wtsrt",_.p,_.Kf),_.Jf.tick("wtsrt_","_wtsrt",_.Lf),_.Jf.tick("tbsd_","wtsrt_"))}
try{_.Mf=_.s;window.chrome&&window.chrome.csi&&(_.Mf=window.Math.floor(window.chrome.csi().pageT),_.Jf&&0<_.Kf&&(_.Jf.tick("_tbnd",_.p,window.chrome.csi().startE),_.Jf.tick("tbnd_","_tbnd",_.Kf)));_.Mf==_.s&&window.gtbExternal&&(_.Mf=window.gtbExternal.pageT());_.Mf==_.s&&window.external&&(_.Mf=window.external.pageT,_.Jf&&0<_.Kf&&(_.Jf.tick("_tbnd",_.p,window.external.startE),_.Jf.tick("tbnd_","_tbnd",_.Kf)));_.Mf&&(window.__gapi_jstiming__.pt=_.Mf)}catch(Nf){};
if(window.__gapi_jstiming__){window.__gapi_jstiming__.Mj={};window.__gapi_jstiming__.qr=1;_.Of=function(a,c,f){var g=a.t[c],h=a.t.start;if(g&&(h||f))return g=a.t[c][0],f!=_.p?h=f:h=h[0],g-h};window.__gapi_jstiming__.getTick=_.Of;window.__gapi_jstiming__.getLabels=function(a){var c=[],f;for(f in a.t)c.push(f);return c};_.Pf=function(a,c,f){var g="";window.__gapi_jstiming__.pt&&(g+="&srt="+window.__gapi_jstiming__.pt);try{window.external&&window.external.tran?g+="&tran="+window.external.tran:window.gtbExternal&&
window.gtbExternal.tran?g+="&tran="+window.gtbExternal.tran():window.chrome&&window.chrome.csi&&(g+="&tran="+window.chrome.csi().tran)}catch(h){}var l=window.chrome;if(l&&(l=l.loadTimes)){l().wasFetchedViaSpdy&&(g+="&p=s");if(l().wasNpnNegotiated){var g=g+"&npn=1",n=l().npnNegotiatedProtocol;n&&(g+="&npnv="+(window.encodeURIComponent||window.escape)(n))}l().wasAlternateProtocolAvailable&&(g+="&apa=1")}var q=a.t,t=q.start,l=[],n=[],w;for(w in q)if("start"!=w&&0!=w.indexOf("_")){var x=q[w][1];x?q[x]&&
n.push(w+"."+(0,_.Of)(a,w,q[x][0])):t&&l.push(w+"."+(0,_.Of)(a,w))}if(c)for(var A in c)g+="&"+A+"="+c[A];(c=f)||(c="https:"==window.document.location.protocol?"https://csi.gstatic.com/csi":"http://csi.gstatic.com/csi");a=[c,"?v=3","&s="+(window.__gapi_jstiming__.sn||"gwidget")+"&action=",a.name,n.length?"&it="+n.join(","):"","",g,"&rt=",l.join(",")].join("");if(!a)return"";var g=new window.Image,E=window.__gapi_jstiming__.qr++;window.__gapi_jstiming__.Mj[E]=g;g.onload=g.onerror=function(){window.__gapi_jstiming__&&
delete window.__gapi_jstiming__.Mj[E]};g.src=a;g=_.s;return a};window.__gapi_jstiming__.report=function(a,c,f){if("prerender"==window.document.webkitVisibilityState){var g=_.u,h=function(){if(!g){c?c.prerender="1":c={prerender:"1"};var l;"prerender"==window.document.webkitVisibilityState?l=_.u:((0,_.Pf)(a,c,f),l=_.r);l&&(g=_.r,window.document.removeEventListener("webkitvisibilitychange",h,_.u))}};window.document.addEventListener("webkitvisibilitychange",h,_.u);return""}return(0,_.Pf)(a,c,f)}};
_.wf=[73,74,77,78];_.vf={g:"gapi_global",m:"gapi_module",w:"gwidget"};_.mf.prototype.key=function(){switch(this.type){case "g":return this.type;case "m":return this.type+"."+this.b;case "w":return this.type+"."+this.name+this.b}};_.tf=new _.mf;_.of=window.navigator.userAgent.match(/iPhone|iPad|Android|PalmWebOS|Maemo|Bada/);_.qf=(0,_.I)(_.ff,"_c",(0,_.L)());_.rf=window.Math.random()<((0,_.N)("csi/rate")||0);(0,_.cf)("blt","bs0","bs1");(0,_.cf)("psi","ps0","ps1");(0,_.cf)("rpcqi","rqe","rqd");
(0,_.cf)("mli","ml0","ml1");(0,_.cf)("mei","me0","me1",_.r);(0,_.cf)("wci","wrs","wdc");(0,_.cf)("wdi","wrs","wrdi");(0,_.cf)("wdt","bs0","wrdt");(0,_.cf)("wri","wrs","wrri",_.r);(0,_.cf)("wrt","bs0","wrrt");(0,_.cf)("wji","wje0","wje1",_.r);(0,_.cf)("wjli","wjl0","wjl1");(0,_.cf)("whi","wh0","wh1",_.r);_.Qf=_.ff.r;if("function"!==typeof _.Qf){for(_.Rf;_.Rf=_.Qf.shift();)_.pf.apply(_.s,_.Rf);_.ff.r=_.pf};
_.Tf=["div"];_.Uf="onload";_.Vf=_.r;_.Ff=_.s;_.Ff=(0,_.N)();(0,_.N)("gwidget");_.Wf=(0,_.xf)("parsetags");_.Uf="explicit"===_.Wf||"onload"===_.Wf?_.Wf:_.Uf;_.Xf=(0,_.xf)("google_analytics");"undefined"!==typeof _.Xf&&(_.Vf=!!_.Xf);_.Yf={};_.Yf.width=[(0,_.yf)(450)];_.Yf.height=[(0,_.yf)(24)];_.Yf.callback=[_.zf];_.Yf.onready=[_.zf];_.Yf.lang=[function(){return(0,_.xf)("lang")||"en-US"},"hl"];_.Yf.iloader=[function(){return _.Qa.ILI},"iloader"];_.Cf=_.Yf;
_.Sf={La:function(a){function c(a){for(var c={},f=0;f<a.length;++f)c[a[f].toLowerCase()]=1;c[h.ss]=1;h.Kq=c}function f(){"onload"===_.Uf&&q.go()}var g,h={};h.Bb=a[0];h.oj=-1;h.Fm="___"+h.Bb+"_";h.ss="g:"+h.Bb;h.Xu="g-"+h.Bb;h.Ql=[];h.Da={};h.hh=[];h.yh=[];a[1]&&(h.ar=a[1]);h.Da=a[2]||{};for(var l in _.Cf)_.Cf.hasOwnProperty(l)&&!h.Da.hasOwnProperty(l)&&(h.Da[l]=_.Cf[l]);a[3]&&(h.hh=a[3]);a[4]&&c(a[4]);a[5]&&(h.ie=a[5]);h.mv=a[7]===_.r;h.gr=a[8];h.Kq||c(_.Tf);if(a=a[6])if("number"==typeof a.length){h.yh=
a;for(var n=a.length-1;0<=n;--n)h.Da[a[n]]=[_.zf]}else for(n in a)a.hasOwnProperty(n)&&!h.Da.hasOwnProperty(n)&&(h.yh.push(n),h.Da[n]=a[n]);h.Ii=function(a){function c(){Zr||(Zr=_.r,f(),$r&&(0,_.gf)("wrrt",lc,mc),(0,_.gf)("wrri",lc,mc))}function f(){as||(as=_.r,Ub.aa(),$r&&(0,_.gf)("wrdt",lc,mc),(0,_.gf)("wrdi",lc,mc))}function g(a){a=a||Ub;var c=(0,_.Pd)(Ub,a.width);c&&ri.style.width!=c.ld&&(ri.style.width=c.ld);if((a=(0,_.Pd)(Ub,a.height))&&ri.style.height!=a.ld)ri.style.height=a.ld}h.oj++;(0,_.gf)("wrs",
h.Bb,(0,window.String)(h.oj));var l=[];h.ie&&(l[0]=a.element,l[1]=a.Ig,h.ie("s",l),a.Ig=l[1]);var n=a.element,q=n.parentNode,t=a.Da;if(0===a.Ig){var qa=window.document.createElement("div");q.insertBefore(qa,n);q.removeChild(n);n=qa}qa=n.style;if(n.id){if(0===n.id.indexOf(h.Fm)){var ea=n.nextSibling;ea&&(ea.getAttribute&&ea.getAttribute("data-gapistub"))&&q.removeChild(ea);qa.cssText=""}}else{var q=n,ea=h.Fm,sa=h.Bb,rb=(0,_.Sa)();window.Object.prototype.hasOwnProperty.call(rb,sa)||(rb[sa]=0);var si=
rb[sa];rb[sa]=si+1;q.id=ea+si}t.height&&(qa.height=t.height+"px");t.width&&(qa.width=t.width+"px");qa.display||(qa.display="inline-block");(0,_.ie)(n);var je=":"+h.Bb;":plus"==je&&(a.he&&a.he.action)&&(je+="_"+a.he.action);var qa={},q=h.hh[0],ea=t.callback,Vb=h.hh[1];if(Vb&&_.Vf)var SA=ea||(0,_.v)(),ea=function(a){var c=Vb(a);if(c&&window._gat)try{var f=window._gat._getTrackerByName("~0");f&&"UA-XXXXX-X"!=f._getAccount()?f._trackSocial("Google",c,a.href||_.s):window._gaq&&window._gaq.push(["_trackSocial",
"Google",c,a.href||_.s])}catch(g){}SA(a)};q&&ea&&(qa[q]=ea);q=h.yh;for(ea=q.length-1;0<=ea;--ea){var Dc=q[ea];(sa=t[Dc])&&(qa[Dc]=sa)}q={};for(Dc in a.he)a.he[Dc]!=_.s&&(q[Dc]=a.he[Dc]);Dc={container:n.id,renderData:a.pr,style:"inline",height:t.height,width:t.width};if(!_.S.qa("attach")){var ea={},ti=_.S.qa("inline"),ui;for(ui in ti)ti.hasOwnProperty(ui)&&(ea[ui]=ti[ui]);ea.open=function(a){var c=window.document.getElementById(a.va.renderData.id);c||(0,_.m)((0,window.Error)("n"));return ti.attach(a,
c)};_.S.la("attach",ea)}Dc.style="attach";h.ie&&(l[2]=Dc,l[3]=q,l[4]=qa,h.ie("i",l),a.Ig=l[1]);var Ub=function(a){var c=_.Af.apply(_.s,[je].concat([].slice.call(arguments,0)));if(t.onready){var f=_.u,g=function(){f||(f=_.r,t.onready.call(_.s))};c.ha("ready",g);c.ha("renderstart",g)}(0,_.Gf)(c);return c}(Dc,q,qa),ri=n;Ub.ha("ready",g);Ub.ha("renderstart",g);Ub.ha("resize",g);var $r=a.Lo,lc=h.Bb,mc=(0,window.String)(h.oj),as=_.u;Ub.ha("renderstart",f);var Zr=_.u;Ub.ha("ready",c);_.R.N("widget-interactive-"+
Ub.id,c);_.R.N("widget-csi-tick-"+Ub.id,function(a,c,f){"wdc"===a||"wci"===a?(0,_.gf)("wdc",lc,mc,f):"wje0"===a||"wji_"===a?(0,_.gf)("wje0",lc,mc,f):"wje1"===a||"wji"===a?(0,_.gf)("wje1",lc,mc,f):"wh0"==a?((0,_.hf)(lc,mc).wh0=f||(new window.Date).getTime(),(0,_.Pe)("wh0",lc,mc)):"wh1"==a&&((0,_.hf)(lc,mc).wh1=f||(new window.Date).getTime(),(0,_.Pe)("wh1",lc,mc))});l[5]=Ub;h.ie&&h.ie("e",l)};g=h;if(n=g.gr)for(a=0;a<n.length;a++)(new window.Image).src=n[a];(0,_.vd)(g.Bb,function(a){var c=a.userParams,
f=a.iframeNode;if((f=f&&f.parentNode)&&1===f.nodeType){f.removeAttribute("data-gwattr");var h=(0,_.Df)(g.Da,c);g.Ql.push({element:f,Da:h,he:(0,_.Bf)(h,(0,_.Df)(g.ar,c)),Ig:3,Lo:!!c["data-onload"],pr:a})}a=g.Ql;for(c=g.Ii;0<a.length;)c(a.shift())});_.Qe[g.Bb]=_.r;var q={I:function(a,c){var f=c||{};f.type=g.Bb;var h=f.type;delete f.type;var l=("string"===typeof a?window.document.getElementById(a):a)||_.p,n={},q;for(q in f)(0,_.Da)(f,q)&&(n[q.toLowerCase()]=f[q]);n.rd=1;(0,_.We)(h,l,n,[],0)},go:function(a){(0,_.Ne)(a, g.Bb)},b:function(){var a=(0,_.Sa)(),c;for(c in a)delete a[c]}},n=g.Bb;a=(0,_.I)(_.Qa,"sws",[]);if(!(0<=_.xb.call(a,n))){if("complete"!==_.fb.readyState)try{f()}catch(t){}(0,_.$c)(f)}return q}};

_.nu=(window.gapi||{}).load;
_.S.Wi("bubble",function(a){(0,_.nu)("iframes-styles-bubble",a)});
_.S.Wi("slide-menu",function(a){(0,_.nu)("iframes-styles-slide-menu",a)});

_.Sv=function(a,c,f){a=(0,_.He)(a);c=(0,_.ue)(c);if(""!=a){if("inline"==a||"only"==a)return a=450,f.width&&(a=120<f.width?f.width:120),{width:a,height:_.ve[c]["false"].height};if("bubble"!=a){if("none"==a)return _.ve[c]["false"];if("pp"==a)return _.Tv}}return _.ve[c]["true"]};_.Tv={width:180,height:35};_.Uv={"0":"plusone"};_.Vv=(0,_.N)("iframes/plusone/preloadUrl");_.Vv&&(_.Uv[8]=_.Vv);(0,_.Le)(_.ze);_.Uv[1]=_.ze;
_.Uv[2]={width:[function(a,c){return c.annotation?(0,_.Sv)(c.annotation,c.size,c).width:_.ve[(0,_.ue)(c.size)][(0,_.we)(c.count,c.size)].width}],height:[function(a,c){return c.annotation?(0,_.Sv)(c.annotation,c.size,c).height:_.ve[(0,_.ue)(c.size)][(0,_.we)(c.count,c.size)].height}]};_.Uv[3]=["onPlusOne",function(a){return"on"==a.state?"+1":_.s}];_.Uv[4]=["div","button"];_.Uv[6]=["onstartinteraction","onendinteraction","onpopup"];_.mb=_.nb=_.Sf.La(_.Uv);
(0,_.O)("gapi.plusone.render",_.nb.I);(0,_.O)("gapi.plusone.go",_.nb.go);(0,_.O)("googleapisv0.plusone.render",_.mb.I);(0,_.O)("googleapisv0.plusone.go",_.mb.go);
});

// Copyright 2002-2013 Google Inc.
