/*

 Copyright (c) 2011 Sencha Labs - Author: Nicolas Garcia Belmonte (http://philogb.github.com/)

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.

*/
(function(){function u(z){return document.getElementById(z)}this.PhiloGL=null;(function(){PhiloGL=function(z,w){function m(r,x,t){var A=r.canvas,a=new PhiloGL.Camera(k.fov,A.width/A.height,k.near,k.far,k);a.update();var b=new PhiloGL.Scene(x,a,c);M=new PhiloGL.WebGL.Application({gl:r,canvas:A,program:x,scene:b,camera:a});x.$$family=="program"&&x.use();f&&PhiloGL.Events.create(M,u.extend(f,{bind:M}));if(d.src.length)new PhiloGL.IO.Textures(u.extend(d,{onComplete:function(){t(M)}}));else t(M)}w=u.merge({context:{},
camera:{fov:45,near:0.1,far:500},program:{from:"defaults",vs:"Default",fs:"Default"},scene:{},textures:{src:[]},events:{},onLoad:u.empty,onError:u.empty},w||{});var o=w.context,k=w.camera,f=w.events,d=w.textures,h=u.splat(w.program),c=w.scene;p=PhiloGL.WebGL.getContext(z,o);if(!p){w.onError("The WebGL context couldn't been initialized");return null}var i={defaults:"fromDefaultShaders",ids:"fromShaderIds",sources:"fromShaderSources",uris:"fromShaderURIs"},j=h.length,l=function(){var r=j,x={},t=false;
return{onSuccess:function(A,a){x[a.id||j-r]=A;r--;if(r===0&&!t)m(p,j==1?A:x,function(b){w.onLoad(b)})},onError:function(A){r--;w.onError(A);t=true}}}();h.forEach(function(r){var x=r.from,t,A;for(A in i)if(x==A){try{t=PhiloGL.Program[i[A]](u.extend(l,r))}catch(a){l.onError(a)}break}if(t)l.onSuccess(t,r)})}})();PhiloGL.unpack=function(z){z=z||aa;["Vec3","Mat4","Quat","Camera","Program","WebGL","O3D","Scene","Shaders","IO","Events","WorkerGroup","Fx","Media"].forEach(function(w){z[w]=PhiloGL[w]});z.gl=
p;z.Utils=u};PhiloGL.version="1.5.2";var p,M,aa=this;u.empty=function(){};u.time=Date.now;u.uid=function(){var z=u.time();return function(){return z++}}();u.extend=function(z,w){for(var m in w)z[m]=w[m];return z};u.type=function(){var z=Object.prototype.toString;return function(w){var m;m=z.call(w);m=m.substr(8,m.length-9).toLowerCase();if(m!="object")return m;if(w.$$family)return w.$$family;return w&&w.nodeName&&w.nodeType==1?"element":m}}();(function(){function z(w){var m=u.type(w);if(m=="object"){m=
{};for(var o in w)m[o]=z(w[o]);return m}else if(m=="array"){m=[];o=0;for(var k=w.length;o<k;o++)m[o]=z(w[o]);return m}else return w}u.merge=function(){for(var w={},m=0,o=arguments.length;m<o;m++){var k=arguments[m];if(u.type(k)=="object")for(var f in k){var d=k[f],h=w[f];w[f]=h&&u.type(d)=="object"&&u.type(h)=="object"?u.merge(h,d):z(d)}}return w}})();u.splat=function(){var z=Array.isArray;return function(w){return z(w)&&w||[w]}}();(function(){function z(m){for(var o in m)this[o]=m[o];this.buffers=
{};this.bufferMemo={};this.frameBuffers={};this.frameBufferMemo={};this.renderBuffers={};this.renderBufferMemo={};this.textures={};this.textureMemo={}}var w={getContext:function(m,o){m=typeof m=="string"?u(m):m;var k;(k=m.getContext("experimental-webgl",o))||(k=m.getContext("webgl",o));if(k&&o&&o.debug){p={};for(var f in k){var d=k[f];p[f]=typeof d=="function"?function(h,c){return function(){console.log(h,Array.prototype.join.call(arguments),Array.prototype.slice.call(arguments));try{var i=c.apply(k,
arguments)}catch(j){throw h+" "+j;}for(var l=[],r;(r=k.getError())!==k.NO_ERROR;)l.push(r);if(l.length)throw l.join();return i}}(f,d):d}}else p=k;if(p)p.get=function(h){return typeof h=="string"?p[h]:h};return p}};z.prototype={$$family:"application",setBuffer:function(m,o,k){if(k===false||k===null){(k=this.bufferMemo[o])&&p.bindBuffer(k.bufferType,null);var f=k&&k.attribute||o;m=m.attributes[f];m!==undefined&&p.disableVertexAttribArray(m)}else{k=u.extend(this.bufferMemo[o]||{bufferType:p.ARRAY_BUFFER,
size:1,dataType:p.FLOAT,stride:0,offset:0,drawType:p.STATIC_DRAW},k||{});f=k.attribute||o;var d=k.bufferType,h=o in this.buffers,c=h?this.buffers[o]:p.createBuffer(),i="value"in k,j=k.value,l=k.size,r=k.dataType,x=k.stride,t=k.offset,A=k.drawType;m=m.attributes[f];var a=m!==undefined;h||(this.buffers[o]=c);a&&p.enableVertexAttribArray(m);p.bindBuffer(d,c);i&&p.bufferData(d,j,A);a&&p.vertexAttribPointer(m,l,r,false,x,t);delete k.value;this.bufferMemo[o]=k;if(a)this.bufferMemo[f]=k;return this}},setBuffers:function(m,
o){for(var k in o)this.setBuffer(m,k,o[k]);return this},setFrameBuffer:function(m,o){if(typeof o!="object")p.bindFramebuffer(p.FRAMEBUFFER,o?this.frameBuffers[m]:null);else{o=u.merge(this.frameBufferMemo[m]||{width:0,height:0,bindToTexture:false,textureOptions:{attachment:p.COLOR_ATTACHMENT0},bindToRenderBuffer:false,renderBufferOptions:{attachment:p.DEPTH_ATTACHMENT}},o||{});var k=o.bindToTexture,f=o.bindToRenderBuffer,d=m in this.frameBuffers,h=d?this.frameBuffers[m]:p.createFramebuffer();p.bindFramebuffer(p.FRAMEBUFFER,
h);d||(this.frameBuffers[m]=h);if(k){k=u.merge({data:{width:o.width,height:o.height}},u.type(k)=="object"?k:{});d=m+"-texture";h=o.textureOptions;this.setTexture(d,k);p.framebufferTexture2D(p.FRAMEBUFFER,h.attachment,this.textureMemo[d].textureType,this.textures[d],0)}if(f){f=u.extend({width:o.width,height:o.height},u.type(f)=="object"?f:{});k=m+"-renderbuffer";d=o.renderBufferOptions;this.setRenderBuffer(k,f);p.framebufferRenderbuffer(p.FRAMEBUFFER,d.attachment,p.RENDERBUFFER,this.renderBuffers[k])}p.bindTexture(p.TEXTURE_2D,
null);p.bindRenderbuffer(p.RENDERBUFFER,null);p.bindFramebuffer(p.FRAMEBUFFER,null);this.frameBufferMemo[m]=o;return this}},setFrameBuffers:function(m){for(var o in m)this.setFrameBuffer(o,m[o]);return this},setRenderBuffer:function(m,o){if(typeof o!="object")p.bindRenderbuffer(p.RENDERBUFFER,o?this.renderBufferMemo[m]:null);else{o=u.extend(this.renderBufferMemo[m]||{storageType:p.DEPTH_COMPONENT16,width:0,height:0},o||{});var k=m in this.renderBuffers,f=k?this.renderBuffers[m]:p.createRenderbuffer(p.RENDERBUFFER);
k||(this.renderBuffers[m]=f);p.bindRenderbuffer(p.RENDERBUFFER,f);p.renderbufferStorage(p.RENDERBUFFER,o.storageType,o.width,o.height);this.renderBufferMemo[m]=o;return this}},setRenderBuffers:function(m){for(var o in m)this.setRenderBuffer(o,m[o]);return this},setTexture:function(m,o){if(!o||typeof o!="object"){p.activeTexture(o||p.TEXTURE0);p.bindTexture(this.textureMemo[m].textureType||p.TEXTURE_2D,this.textures[m])}else{if(o.data&&o.data.type===p.FLOAT)if(!p.getExtension("OES_texture_float"))throw"OES_texture_float is not supported";
o=u.merge(this.textureMemo[m]||{textureType:p.TEXTURE_2D,pixelStore:[{name:p.UNPACK_FLIP_Y_WEBGL,value:true},{name:p.UNPACK_ALIGNMENT,value:1}],parameters:[{name:p.TEXTURE_MAG_FILTER,value:p.NEAREST},{name:p.TEXTURE_MIN_FILTER,value:p.NEAREST},{name:p.TEXTURE_WRAP_S,value:p.CLAMP_TO_EDGE},{name:p.TEXTURE_WRAP_T,value:p.CLAMP_TO_EDGE}],data:{format:p.RGBA,value:false,type:p.UNSIGNED_BYTE,width:0,height:0,border:0}},o||{});var k="textureType"in o?o.textureType=p.get(o.textureType):p.TEXTURE_2D,f="textureTarget"in
o?o.textureTarget=p.get(o.textureTarget):k,d=k==p.TEXTURE_CUBE_MAP,h=m in this.textures,c=h?this.textures[m]:p.createTexture(),i=o.pixelStore,j=o.parameters,l=o.data,r=l.value,x=l.type,t=l.format,A=!!l.value;h||(this.textures[m]=c);p.bindTexture(k,c);h||i.forEach(function(a){a.name=typeof a.name=="string"?p.get(a.name):a.name;p.pixelStorei(a.name,a.value)});if(A)if(d)for(c=0;c<6;++c)(l.width||l.height)&&!r.width&&!r.height?p.texImage2D(f[c],0,t,l.width,l.height,l.border,t,x,r[c]):p.texImage2D(f[c],
0,t,t,x,r[c]);else(l.width||l.height)&&!r.width&&!r.height?p.texImage2D(f,0,t,l.width,l.height,l.border,t,x,r):p.texImage2D(f,0,t,t,x,r);else if(l.width||l.height)p.texImage2D(f,0,t,l.width,l.height,l.border,t,x,null);if(!h)for(c=0;c<j.length;c++){f=j[c];f.name=p.get(f.name);f.value=p.get(f.value);p.texParameteri(k,f.name,f.value);f.generateMipmap&&p.generateMipmap(k)}o.isCube=d;if(A)o.data.value=false;this.textureMemo[m]=o;return this}},setTextures:function(m){for(var o in m)this.setTexture(o,m[o]);
return this},use:function(m){p.useProgram(m.program);this.usedProgram=m;return this}};w.Application=z;(function(){try{var m=document.createElement("canvas");PhiloGL.hasWebGL=function(){return!!(window.WebGLRenderingContext&&(m.getContext("webgl")||m.getContext("experimental-webgl")))}}catch(o){PhiloGL.hasWebGL=function(){return false}}PhiloGL.hasExtension=function(k){if(!PhiloGL.hasWebGL())return false;var f=document.createElement("canvas");return(f.getContext("webgl")||f.getContext("experimental-webgl")).getExtension(k)}})();
PhiloGL.WebGL=w})();(function(){function z(a){return{get:function(){return this[a]},set:function(b){this[a]=b},configurable:false,enumerable:false}}var w=Math.sqrt,m=Math.sin,o=Math.cos,k=Math.tan,f=Math.PI,d=Array.prototype.slice,h=this.Float32Array,c=function(){if(!h||!h.call)return Array;try{h.call({},10)}catch(a){return Array}return h}(),i=c!=Array,j=function(a,b,g){if(i){h.call(this,3);this[0]=a||0;this[1]=b||0;this[2]=g||0}else this.push(a||0,b||0,g||0);this.typedContainer=new h(3)};j.create=
function(){return new h(3)};j.prototype=Object.create(c.prototype,{$$family:{value:"Vec3"},x:z(0),y:z(1),z:z(2)});var l={setVec3:function(a,b){a[0]=b[0];a[1]=b[1];a[2]=b[2];return a},set:function(a,b,g,n){a[0]=b;a[1]=g;a[2]=n;return a},add:function(a,b){return new j(a[0]+b[0],a[1]+b[1],a[2]+b[2])},$add:function(a,b){a[0]+=b[0];a[1]+=b[1];a[2]+=b[2];return a},add2:function(a,b,g){a[0]=b[0]+g[0];a[1]=b[1]+g[1];a[2]=b[2]+g[2];return a},sub:function(a,b){return new j(a[0]-b[0],a[1]-b[1],a[2]-b[2])},$sub:function(a,
b){a[0]-=b[0];a[1]-=b[1];a[2]-=b[2];return a},sub2:function(a,b,g){a[0]=b[0]-g[0];a[1]=b[1]-g[1];a[2]=b[2]-g[2];return a},scale:function(a,b){return new j(a[0]*b,a[1]*b,a[2]*b)},$scale:function(a,b){a[0]*=b;a[1]*=b;a[2]*=b;return a},neg:function(a){return new j(-a[0],-a[1],-a[2])},$neg:function(a){a[0]=-a[0];a[1]=-a[1];a[2]=-a[2];return a},unit:function(a){var b=j.norm(a);if(b>0)return j.scale(a,1/b);return j.clone(a)},$unit:function(a){var b=j.norm(a);if(b>0)return j.$scale(a,1/b);return a},cross:function(a,
b){var g=a[0],n=a[1],q=a[2],s=b[0],v=b[1],y=b[2];return new j(n*y-q*v,q*s-g*y,g*v-n*s)},$cross:function(a,b){var g=a[0],n=a[1],q=a[2],s=b[0],v=b[1],y=b[2];a[0]=n*y-q*v;a[1]=q*s-g*y;a[2]=g*v-n*s;return a},distTo:function(a,b){var g=a[0]-b[0],n=a[1]-b[1],q=a[2]-b[2];return w(g*g+n*n+q*q)},distToSq:function(a,b){var g=a[0]-b[0],n=a[1]-b[1],q=a[2]-b[2];return g*g+n*n+q*q},norm:function(a){var b=a[0],g=a[1];a=a[2];return w(b*b+g*g+a*a)},normSq:function(a){var b=a[0],g=a[1];a=a[2];return b*b+g*g+a*a},dot:function(a,
b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]},clone:function(a){return a.$$family?new j(a[0],a[1],a[2]):j.setVec3(new h(3),a)},toFloat32Array:function(a){var b=a.typedContainer;if(!b)return a;b[0]=a[0];b[1]=a[1];b[2]=a[2];return b}},r=j.prototype,x;for(x in l){j[x]=l[x];r[x]=function(a){return function(){var b=d.call(arguments);b.unshift(this);return j[a].apply(j,b)}}(x)}var t=function(a,b,g,n,q,s,v,y,B,C,D,E,G,I,J,H){c.call(this,16);this.length=16;typeof a=="number"?this.set(a,b,g,n,q,s,v,y,B,C,D,E,G,
I,J,H):this.id();this.typedContainer=new h(16)};t.create=function(){return new h(16)};t.prototype=Object.create(c.prototype,{$$family:{value:"Mat4"},n11:z(0),n12:z(4),n13:z(8),n14:z(12),n21:z(1),n22:z(5),n23:z(9),n24:z(13),n31:z(2),n32:z(6),n33:z(10),n34:z(14),n41:z(3),n42:z(7),n43:z(11),n44:z(15)});l={id:function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=1;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a},clone:function(a){return a.$$family?new t(a[0],a[4],a[8],
a[12],a[1],a[5],a[9],a[13],a[2],a[6],a[10],a[14],a[3],a[7],a[11],a[15]):new h(a)},set:function(a,b,g,n,q,s,v,y,B,C,D,E,G,I,J,H,F){a[0]=b;a[4]=g;a[8]=n;a[12]=q;a[1]=s;a[5]=v;a[9]=y;a[13]=B;a[2]=C;a[6]=D;a[10]=E;a[14]=G;a[3]=I;a[7]=J;a[11]=H;a[15]=F;return a},mulVec3:function(a,b){var g=j.clone(b);return t.$mulVec3(a,g)},$mulVec3:function(a,b){var g=b[0],n=b[1],q=b[2],s=1/(a[3]*g+a[7]*n+a[11]*q+a[15]);b[0]=(a[0]*g+a[4]*n+a[8]*q+a[12])*s;b[1]=(a[1]*g+a[5]*n+a[9]*q+a[13])*s;b[2]=(a[2]*g+a[6]*n+a[10]*
q+a[14])*s;return b},mulMat42:function(a,b,g){var n=b[0],q=b[1],s=b[2],v=b[3],y=b[4],B=b[5],C=b[6],D=b[7],E=b[8],G=b[9],I=b[10],J=b[11],H=b[12],F=b[13],N=b[14];b=b[15];var K=g[0],L=g[1],P=g[2],Q=g[3],R=g[4],U=g[5],V=g[6],W=g[7],S=g[8],T=g[9],X=g[10],O=g[11],Y=g[12],Z=g[13],$=g[14];g=g[15];a[0]=K*n+L*y+P*E+Q*H;a[1]=K*q+L*B+P*G+Q*F;a[2]=K*s+L*C+P*I+Q*N;a[3]=K*v+L*D+P*J+Q*b;a[4]=R*n+U*y+V*E+W*H;a[5]=R*q+U*B+V*G+W*F;a[6]=R*s+U*C+V*I+W*N;a[7]=R*v+U*D+V*J+W*b;a[8]=S*n+T*y+X*E+O*H;a[9]=S*q+T*B+X*G+O*F;a[10]=
S*s+T*C+X*I+O*N;a[11]=S*v+T*D+X*J+O*b;a[12]=Y*n+Z*y+$*E+g*H;a[13]=Y*q+Z*B+$*G+g*F;a[14]=Y*s+Z*C+$*I+g*N;a[15]=Y*v+Z*D+$*J+g*b;return a},mulMat4:function(a,b){var g=t.clone(a);return t.mulMat42(g,a,b)},$mulMat4:function(a,b){return t.mulMat42(a,a,b)},add:function(a,b){var g=t.clone(a);return t.$add(g,b)},$add:function(a,b){a[0]+=b[0];a[1]+=b[1];a[2]+=b[2];a[3]+=b[3];a[4]+=b[4];a[5]+=b[5];a[6]+=b[6];a[7]+=b[7];a[8]+=b[8];a[9]+=b[9];a[10]+=b[10];a[11]+=b[11];a[12]+=b[12];a[13]+=b[13];a[14]+=b[14];a[15]+=
b[15];return a},transpose:function(a){a=t.clone(a);return t.$transpose(a)},$transpose:function(a){var b=a[8],g=a[12],n=a[1],q=a[9],s=a[13],v=a[2],y=a[6],B=a[14],C=a[3],D=a[7],E=a[11];a[1]=a[4];a[2]=b;a[3]=g;a[4]=n;a[6]=q;a[7]=s;a[8]=v;a[9]=y;a[11]=B;a[12]=C;a[13]=D;a[14]=E;return a},rotateAxis:function(a,b,g){a=t.clone(a);return t.$rotateAxis(a,b,g)},$rotateAxis:function(a,b,g){var n=m(b),q=o(b),s=1-q,v=g[0],y=g[1],B=g[2];g=v*v*s+q;b=v*y*s+B*n;var C=v*B*s-y*n,D=y*v*s-B*n,E=y*y*s+q,G=y*B*s+v*n,I=v*
B*s+y*n;n=y*B*s-v*n;q=B*B*s+q;s=a[0];v=a[1];y=a[2];B=a[3];var J=a[4],H=a[5],F=a[6],N=a[7],K=a[8],L=a[9],P=a[10],Q=a[11];a[0]=s*g+J*b+K*C;a[1]=v*g+H*b+L*C;a[2]=y*g+F*b+P*C;a[3]=B*g+N*b+Q*C;a[4]=s*D+J*E+K*G;a[5]=v*D+H*E+L*G;a[6]=y*D+F*E+P*G;a[7]=B*D+N*E+Q*G;a[8]=s*I+J*n+K*q;a[9]=v*I+H*n+L*q;a[10]=y*I+F*n+P*q;a[11]=B*I+N*n+Q*q;return a},rotateXYZ:function(a,b,g,n){a=t.clone(a);return t.$rotateXYZ(a,b,g,n)},$rotateXYZ:function(a,b,g,n){var q=a[0],s=a[1],v=a[2],y=a[3],B=a[4],C=a[5],D=a[6],E=a[7],G=a[8],
I=a[9],J=a[10],H=a[11],F=o(b),N=o(g),K=o(n);b=m(b);var L=m(g),P=m(n);n=N*K;g=-F*P+b*L*K;var Q=b*P+F*L*K,R=N*P,U=F*K+b*L*P;K=-b*K+F*L*P;L=-L;b*=N;F*=N;a[0]=q*n+B*R+G*L;a[1]=s*n+C*R+I*L;a[2]=v*n+D*R+J*L;a[3]=y*n+E*R+H*L;a[4]=q*g+B*U+G*b;a[5]=s*g+C*U+I*b;a[6]=v*g+D*U+J*b;a[7]=y*g+E*U+H*b;a[8]=q*Q+B*K+G*F;a[9]=s*Q+C*K+I*F;a[10]=v*Q+D*K+J*F;a[11]=y*Q+E*K+H*F;return a},translate:function(a,b,g,n){a=t.clone(a);return t.$translate(a,b,g,n)},$translate:function(a,b,g,n){a[12]=a[0]*b+a[4]*g+a[8]*n+a[12];a[13]=
a[1]*b+a[5]*g+a[9]*n+a[13];a[14]=a[2]*b+a[6]*g+a[10]*n+a[14];a[15]=a[3]*b+a[7]*g+a[11]*n+a[15];return a},scale:function(a,b,g,n){a=t.clone(a);return t.$scale(a,b,g,n)},$scale:function(a,b,g,n){a[0]*=b;a[1]*=b;a[2]*=b;a[3]*=b;a[4]*=g;a[5]*=g;a[6]*=g;a[7]*=g;a[8]*=n;a[9]*=n;a[10]*=n;a[11]*=n;return a},invert:function(a){a=t.clone(a);return t.$invert(a)},$invert:function(a){var b=a[0],g=a[1],n=a[2],q=a[3],s=a[4],v=a[5],y=a[6],B=a[7],C=a[8],D=a[9],E=a[10],G=a[11],I=a[12],J=a[13],H=a[14],F=a[15],N=b*v-
g*s,K=b*y-n*s,L=b*B-q*s,P=g*y-n*v,Q=g*B-q*v,R=n*B-q*y,U=C*J-D*I,V=C*H-E*I,W=C*F-G*I,S=D*H-E*J,T=D*F-G*J,X=E*F-G*H,O=1/(N*X-K*T+L*S+P*W-Q*V+R*U);a[0]=(+v*X-y*T+B*S)*O;a[1]=(-g*X+n*T-q*S)*O;a[2]=(+J*R-H*Q+F*P)*O;a[3]=(-D*R+E*Q-G*P)*O;a[4]=(-s*X+y*W-B*V)*O;a[5]=(+b*X-n*W+q*V)*O;a[6]=(-I*R+H*L-F*K)*O;a[7]=(+C*R-E*L+G*K)*O;a[8]=(+s*T-v*W+B*U)*O;a[9]=(-b*T+g*W-q*U)*O;a[10]=(+I*Q-J*L+F*N)*O;a[11]=(-C*Q+D*L-G*N)*O;a[12]=(-s*S+v*V-y*U)*O;a[13]=(+b*S-g*V+n*U)*O;a[14]=(-I*P+J*K-H*N)*O;a[15]=(+C*P-D*K+E*N)*O;
return a},lookAt:function(a,b,g,n){g=j.sub(b,g);g.$unit();n=j.cross(n,g);n.$unit();var q=j.cross(g,n);q.$unit();return t.set(a,n[0],n[1],n[2],-n.dot(b),q[0],q[1],q[2],-q.dot(b),g[0],g[1],g[2],-g.dot(b),0,0,0,1)},frustum:function(a,b,g,n,q,s,v){var y=g-b,B=q-n,C=v-s;a[0]=s*2/y;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=s*2/B;a[6]=0;a[7]=0;a[8]=(g+b)/y;a[9]=(q+n)/B;a[10]=-(v+s)/C;a[11]=-1;a[12]=0;a[13]=0;a[14]=-(v*s*2)/C;a[15]=0;return a},perspective:function(a,b,g,n,q){b=n*k(b*f/360);var s=-b;return t.frustum(a,
s*g,b*g,s,b,n,q)},ortho:function(a,b,g,n,q,s,v){var y=g-b,B=q-n,C=v-s;a[0]=2/y;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=2/B;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=-2/C;a[11]=0;a[12]=-(b+g)/y;a[13]=-(q+n)/B;a[14]=-(v+s)/C;a[15]=1;return a},toFloat32Array:function(a){var b=a.typedContainer;if(!b)return a;b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=a[12];b[13]=a[13];b[14]=a[14];b[15]=a[15];return b}};r=t.prototype;for(x in l){t[x]=
l[x];r[x]=function(a){return function(){var b=d.call(arguments);b.unshift(this);return t[a].apply(t,b)}}(x)}var A=function(a,b,g,n){c.call(this,4);this[0]=a||0;this[1]=b||0;this[2]=g||0;this[3]=n||0;this.typedContainer=new h(4)};A.create=function(){return new h(4)};l={setQuat:function(a,b){a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3];return a},set:function(a,b,g,n,q){a[0]=b||0;a[1]=g||0;a[2]=n||0;a[3]=q||0;return a},clone:function(a){return a.$$family?new A(a[0],a[1],a[2],a[3]):A.setQuat(new h(4),a)},
neg:function(a){return new A(-a[0],-a[1],-a[2],-a[3])},$neg:function(a){a[0]=-a[0];a[1]=-a[1];a[2]=-a[2];a[3]=-a[3];return a},add:function(a,b){return new A(a[0]+b[0],a[1]+b[1],a[2]+b[2],a[3]+b[3])},$add:function(a,b){a[0]+=b[0];a[1]+=b[1];a[2]+=b[2];a[3]+=b[3];return a},sub:function(a,b){return new A(a[0]-b[0],a[1]-b[1],a[2]-b[2],a[3]-b[3])},$sub:function(a,b){a[0]-=b[0];a[1]-=b[1];a[2]-=b[2];a[3]-=b[3];return a},scale:function(a,b){return new A(a[0]*b,a[1]*b,a[2]*b,a[3]*b)},$scale:function(a,b){a[0]*=
b;a[1]*=b;a[2]*=b;a[3]*=b;return a},mulQuat:function(a,b){var g=a[0],n=a[1],q=a[2],s=a[3],v=b[0],y=b[1],B=b[2],C=b[3];return new A(s*v+g*C+n*B-q*y,s*y+n*C+q*v-g*B,s*B+q*C+g*y-n*v,s*C-g*v-n*y-q*B)},$mulQuat:function(a,b){var g=a[0],n=a[1],q=a[2],s=a[3],v=b[0],y=b[1],B=b[2],C=b[3];a[0]=s*v+g*C+n*B-q*y;a[1]=s*y+n*C+q*v-g*B;a[2]=s*B+q*C+g*y-n*v;a[3]=s*C-g*v-n*y-q*B;return a},divQuat:function(a,b){var g=a[0],n=a[1],q=a[2],s=a[3],v=b[0],y=b[1],B=b[2],C=b[3],D=1/(C*C+v*v+y*y+B*B);return new A((g*C-s*v-n*
B+q*y)*D,(g*B-s*y+n*C-q*v)*D,(n*v+q*C-s*B-g*y)*D,(s*C+g*v+n*y+q*B)*D)},$divQuat:function(a,b){var g=a[0],n=a[1],q=a[2],s=a[3],v=b[0],y=b[1],B=b[2],C=b[3],D=1/(C*C+v*v+y*y+B*B);a[0]=(g*C-s*v-n*B+q*y)*D;a[1]=(g*B-s*y+n*C-q*v)*D;a[2]=(n*v+q*C-s*B-g*y)*D;a[3]=(s*C+g*v+n*y+q*B)*D;return a},invert:function(a){var b=a[0],g=a[1],n=a[2];a=a[3];var q=1/(b*b+g*g+n*n+a*a);return new A(-b*q,-g*q,-n*q,a*q)},$invert:function(a){var b=a[0],g=a[1],n=a[2],q=a[3],s=1/(b*b+g*g+n*n+q*q);a[0]=-b*s;a[1]=-g*s;a[2]=-n*s;
a[3]=q*s;return a},norm:function(a){var b=a[0],g=a[1],n=a[2];a=a[3];return w(b*b+g*g+n*n+a*a)},normSq:function(a){var b=a[0],g=a[1],n=a[2];a=a[3];return b*b+g*g+n*n+a*a},unit:function(a){return A.scale(a,1/A.norm(a))},$unit:function(a){return A.$scale(a,1/A.norm(a))},conjugate:function(a){return new A(-a[0],-a[1],-a[2],a[3])},$conjugate:function(a){a[0]=-a[0];a[1]=-a[1];a[2]=-a[2];return a}};r=A.prototype={};for(x in l){A[x]=l[x];r[x]=function(a){return function(){var b=d.call(arguments);b.unshift(this);
return A[a].apply(A,b)}}(x)}j.fromQuat=function(a){return new j(a[0],a[1],a[2])};A.fromVec3=function(a,b){return new A(a[0],a[1],a[2],b||0)};A.fromMat4=function(a){var b,g,n;if(a[0]>a[5]&&a[0]>a[10]){b=0;g=1;n=2}else if(a[5]>a[0]&&a[5]>a[10]){b=1;g=2;n=0}else{b=2;g=0;n=1}var q=w(1+a[b*5]-a[g*5]-a[n*5]),s=new A;s[b]=0.5*q;s[g]=0.5*(a["n"+g+""+b]+a["n"+b+""+g])/q;s[n]=0.5*(a["n"+b+""+n]+a["n"+n+""+b])/q;s[3]=0.5*(a["n"+g+""+n]-a["n"+n+""+g])/q;return s};A.fromXRotation=function(a){return new A(m(a/
2),0,0,o(a/2))};A.fromYRotation=function(a){return new A(0,m(a/2),0,o(a/2))};A.fromZRotation=function(a){return new A(0,0,m(a/2),o(a/2))};A.fromAxisRotation=function(a,b){var g=a[0],n=a[1],q=a[2],s=1/w(g*g+n*n+q*q),v=m(b/2),y=o(b/2);return new A(v*g*s,v*n*s,v*q*s,y)};t.fromQuat=function(a){var b=a[3],g=a[0],n=a[1];a=a[2];return new t(b*b+g*g-n*n-a*a,2*g*n-2*b*a,2*g*a+2*b*n,0,2*g*n+2*b*a,b*b-g*g+n*n-a*a,2*n*a-2*b*g,0,2*g*a-2*b*n,2*n*a+2*b*g,b*b-g*g-n*n+a*a,0,0,0,0,1)};PhiloGL.Vec3=j;PhiloGL.Mat4=t;
PhiloGL.Quat=A})();(function(){function z(f){return f!==true?f:false}var w=function(f){f=f.getBoundingClientRect();return{x:f.left,y:f.top,bbox:f}},m={get:function(f,d){return f||(d||window).event},getWheel:function(f){return f.wheelDelta?f.wheelDelta/120:-(f.detail||0)/3},getKey:function(f){var d=f.which||f.keyCode,h;a:{h=k.Keys;for(var c in h)if(h[c]==d){h=c;break a}h=void 0}c=d-111;if(c>0&&c<13)h="f"+c;h=h||String.fromCharCode(d).toLowerCase();return{code:d,key:h,shift:f.shiftKey,control:f.ctrlKey,
alt:f.altKey,meta:f.metaKey}},isRightClick:function(f){return f.which==3||f.button==2},getPos:function(f,d){d=d||window;f=f||d.event;var h=d.document;h=h.documentElement||h.body;if(f.touches&&f.touches.length)f=f.touches[0];return{x:f.pageX||f.clientX+h.scrollLeft,y:f.pageY||f.clientY+h.scrollTop}},stop:function(f){f.stopPropagation&&f.stopPropagation();f.cancelBubble=true;if(f.preventDefault)f.preventDefault();else f.returnValue=false}},o=function(f,d){var h=f.canvas;this.scene=f.scene;this.domElem=
h;this.pos=w(h);this.opt=this.callbacks=d;this.size={width:h.width||h.offsetWidth,height:h.height||h.offsetHeight};this.attachEvents()};o.prototype={hovered:false,pressed:false,touched:false,touchMoved:false,moved:false,attachEvents:function(){var f=this.domElem,d=this;if(this.opt.disableContextMenu)f.oncontextmenu=function(){return false};["mouseup","mousedown","mousemove","mouseover","mouseout","touchstart","touchmove","touchend"].forEach(function(c){f.addEventListener(c,function(i,j){d[c](d.eventInfo(c,
i,j))},false)});["keydown","keyup"].forEach(function(c){document.addEventListener(c,function(i,j){d[c](d.eventInfo(c,i,j))},false)});var h="";h=!document.getBoxObjectFor&&window.mozInnerScreenX==null?"mousewheel":"DOMMouseScroll";f.addEventListener(h,function(c,i){d.mousewheel(d.eventInfo("mousewheel",c,i))},false)},eventInfo:function(f,d,h){var c=this.domElem,i=this.scene,j=this.opt,l=this.getSize(),r=j.relative,x=j.centerOrigin,t=j.cachePosition&&this.pos||w(c),A=m.get(d,h),a=m.getPos(d,h);d={};
h=a.x;c=a.y;if(r){h-=t.x;c-=t.y;if(x){h-=l.width/2;c-=l.height/2;c*=-1}}switch(f){case "mousewheel":d.wheel=m.getWheel(A);break;case "keydown":case "keyup":u.extend(d,m.getKey(A));break;case "mouseup":d.isRightClick=m.isRightClick(A)}var b;u.extend(d,{x:h,y:c,cache:false,stop:function(){m.stop(A)},getTarget:function(){if(b)return b;return b=!j.picking||i.pick(a.x-t.x,a.y-t.y,j.lazyPicking)||true}});d.event=A;return d},getSize:function(){if(this.cacheSize)return this.size;var f=this.domElem;return{width:f.width||
f.offsetWidth,height:f.height||f.offsetHeight}},mouseup:function(f){if(!this.moved)if(f.isRightClick)this.callbacks.onRightClick(f,this.hovered);else this.callbacks.onClick(f,z(this.pressed));if(this.pressed){if(this.moved)this.callbacks.onDragEnd(f,z(this.pressed));else this.callbacks.onDragCancel(f,z(this.pressed));this.pressed=this.moved=false}},mouseout:function(f){for(var d=f.relatedTarget,h=this.domElem;d&&d.parentNode;){if(h==d.parentNode)return;d=d.parentNode}if(this.hovered){this.callbacks.onMouseLeave(f,
this.hovered);this.hovered=false}if(this.pressed&&this.moved){this.callbacks.onDragEnd(f);this.pressed=this.moved=false}},mouseover:function(){},mousemove:function(f){if(this.pressed){this.moved=true;this.callbacks.onDragMove(f,z(this.pressed))}else{if(this.hovered){var d=z(f.getTarget());if(!d||d.hash!=this.hash){this.callbacks.onMouseLeave(f,this.hovered);if(this.hash=this.hovered=d){this.hash=d.hash;this.callbacks.onMouseEnter(f,this.hovered)}}else this.callbacks.onMouseMove(f,this.hovered)}else if(this.hash=
this.hovered=z(f.getTarget())){this.hash=this.hovered.hash;this.callbacks.onMouseEnter(f,this.hovered)}if(!this.opt.picking)this.callbacks.onMouseMove(f)}},mousewheel:function(f){this.callbacks.onMouseWheel(f)},mousedown:function(f){this.pressed=f.getTarget();this.callbacks.onDragStart(f,z(this.pressed))},touchstart:function(f){this.touched=f.getTarget();this.callbacks.onTouchStart(f,z(this.touched))},touchmove:function(f){if(this.touched){this.touchMoved=true;this.callbacks.onTouchMove(f,z(this.touched))}},
touchend:function(f){if(this.touched){if(this.touchMoved)this.callbacks.onTouchEnd(f,z(this.touched));else this.callbacks.onTouchCancel(f,z(this.touched));this.touched=this.touchMoved=false}},keydown:function(f){this.callbacks.onKeyDown(f)},keyup:function(f){this.callbacks.onKeyUp(f)}};var k={};k.create=function(f,d){d=u.extend({cachePosition:true,cacheSize:true,relative:true,centerOrigin:true,disableContextMenu:true,bind:false,picking:false,lazyPicking:false,onClick:u.empty,onRightClick:u.empty,
onDragStart:u.empty,onDragMove:u.empty,onDragEnd:u.empty,onDragCancel:u.empty,onTouchStart:u.empty,onTouchMove:u.empty,onTouchEnd:u.empty,onTouchCancel:u.empty,onMouseMove:u.empty,onMouseEnter:u.empty,onMouseLeave:u.empty,onMouseWheel:u.empty,onKeyDown:u.empty,onKeyUp:u.empty},d||{});var h=d.bind;if(h)for(var c in d)c.match(/^on[a-zA-Z0-9]+$/)&&function(i,j){d[i]=function(){return j.apply(h,Array.prototype.slice.call(arguments))}}(c,d[c]);new o(f,d);f.events=d};k.Keys={enter:13,up:38,down:40,left:37,
right:39,esc:27,space:32,backspace:8,tab:9,"delete":46};PhiloGL.Events=k})();(function(){function z(d,h){return u.merge(h||{},d.length==2?{vs:d[0],fs:d[1]}:d[0]||{})}var w=function(d,h,c){var i=d.createShader(c);if(i==null)throw"Error creating the shader with shader type: "+c;d.shaderSource(i,h);d.compileShader(i);if(!d.getShaderParameter(i,d.COMPILE_STATUS)){h=d.getShaderInfoLog(i);d.deleteShader(i);throw"Error while compiling the shader "+h;}return i},m=function(d){var h=d.lastIndexOf("/");return h==
"/"?"./":d.substr(0,h+1)},o=function(d,h,c,i,j){j=j||{};var l;if(l=h.match(/#include "(.*?)"/)){var r=PhiloGL.IO.XHR,x=m(d)+l[1];j[x]&&i("Recursive include");(new r({url:x,noCache:true,onError:function(t){i("Load included file `"+x+"` failed: Code "+t)},onSuccess:function(t){j[x]=true;return o(x,t,function(A){delete j[x];h=h.replace(/#include ".*?"/,A);h=h.replace(/\sHAS_EXTENSION\s*\(\s*([A-Za-z_\-0-9]+)\s*\)/g,function(a,b){return p.getExtension(b)?" 1 ":" 0 "});return o(x,h,c,i,j)},i,j)}})).send();
return null}else return c(h)},k=function(d,h,c){var i=p.getUniformLocation(d,h.name);d=h.type;var j=false,l=true,r,x;if(h.size>1&&c)switch(d){case p.FLOAT:r=p.uniform1fv;x=Float32Array;l=false;break;case p.INT:case p.BOOL:case p.SAMPLER_2D:case p.SAMPLER_CUBE:r=p.uniform1iv;x=Uint16Array;l=false}if(l)switch(d){case p.FLOAT:r=p.uniform1f;break;case p.FLOAT_VEC2:r=p.uniform2fv;x=c?Float32Array:new Float32Array(2);break;case p.FLOAT_VEC3:r=p.uniform3fv;x=c?Float32Array:new Float32Array(3);break;case p.FLOAT_VEC4:r=
p.uniform4fv;x=c?Float32Array:new Float32Array(4);break;case p.INT:case p.BOOL:case p.SAMPLER_2D:case p.SAMPLER_CUBE:r=p.uniform1i;break;case p.INT_VEC2:case p.BOOL_VEC2:r=p.uniform2iv;x=c?Uint16Array:new Uint16Array(2);break;case p.INT_VEC3:case p.BOOL_VEC3:r=p.uniform3iv;x=c?Uint16Array:new Uint16Array(3);break;case p.INT_VEC4:case p.BOOL_VEC4:r=p.uniform4iv;x=c?Uint16Array:new Uint16Array(4);break;case p.FLOAT_MAT2:j=true;r=p.uniformMatrix2fv;break;case p.FLOAT_MAT3:j=true;r=p.uniformMatrix3fv;
break;case p.FLOAT_MAT4:j=true;r=p.uniformMatrix4fv}if(r.bind)r=r.bind(p);else{var t=r;r=function(){t.apply(p,arguments)}}return c&&x?function(A){r(i,new x(A))}:j?function(A){r(i,false,A.toFloat32Array())}:x?function(A){x.set(A.toFloat32Array?A.toFloat32Array():A);r(i,x)}:function(A){r(i,A)};throw"Unknown type: "+d;},f=function(d,h){var c=p,i=c.createProgram();c.attachShader(i,w(c,d,c.VERTEX_SHADER));c.attachShader(i,w(c,h,c.FRAGMENT_SHADER));c.linkProgram(i);if(!c.getProgramParameter(i,c.LINK_STATUS))throw"Error linking the shader: "+
c.getProgramInfoLog(i);if(!i)return false;c={};for(var j={},l,r,x=p.getProgramParameter(i,p.ACTIVE_ATTRIBUTES),t=0;t<x;t++){l=p.getActiveAttrib(i,t);r=l.name;l=p.getAttribLocation(i,l.name);c[r]=l}x=p.getProgramParameter(i,p.ACTIVE_UNIFORMS);for(t=0;t<x;t++){l=p.getActiveUniform(i,t);r=l.name;r=r[r.length-1]=="]"?r.substr(0,r.length-3):r;j[r]=k(i,l,l.name!=r)}this.program=i;this.attributes=c;this.attributeEnabled={};this.uniforms=j};f.prototype={$$family:"program",setUniform:function(d,h){if(this.uniforms[d])this.uniforms[d](h);
return this},setUniforms:function(d){for(var h in d)this.setUniform(h,d[h]);return this}};["setBuffer","setBuffers","use"].forEach(function(d){f.prototype[d]=function(){var h=Array.prototype.slice.call(arguments);h.unshift(this);M[d].apply(M,h);return this}});["setFrameBuffer","setFrameBuffers","setRenderBuffer","setRenderBuffers","setTexture","setTextures"].forEach(function(d){f.prototype[d]=function(){M[d].apply(M,arguments);return this}});f.fromShaderIds=function(){var d=z(arguments),h=u(d.vs),
c=u(d.fs);return o(d.path,h.innerHTML,function(i){return o(d.path,c.innerHTML,function(j){d.onSuccess(new f(i,j),d)})})};f.fromShaderSources=function(){var d=z(arguments,{path:"./"});return o(d.path,d.vs,function(h){return o(d.path,d.fs,function(c){try{var i=new f(h,c);if(d.onSuccess)d.onSuccess(i,d);else return i}catch(j){if(d.onError)d.onError(j,d);else throw j;}})})};f.fromDefaultShaders=function(d){d=d||{};var h=d.fs||"Default",c=PhiloGL.Shaders;d.vs=c.Vertex[d.vs||"Default"];d.fs=c.Fragment[h];
return PhiloGL.Program.fromShaderSources(d)};f.fromShaderURIs=function(d){d=u.merge({path:"",vs:"",fs:"",noCache:false,onSuccess:u.empty,onError:u.empty},d||{});var h=d.path+d.vs,c=d.path+d.fs;(new PhiloGL.IO.XHR.Group({urls:[h,c],noCache:d.noCache,onError:function(i){d.onError(i)},onComplete:function(i){try{return o(h,i[0],function(l){return o(c,i[1],function(r){d.vs=l;d.fs=r;return f.fromShaderSources(d)},d.onError)},d.onError)}catch(j){d.onError(j,d)}}})).send()};PhiloGL.Program=f})();(function(){var z=
{},w=function(k){this.opt=k=u.merge({url:"http://philogljs.org/",method:"GET",async:true,noCache:false,sendAsBinary:false,responseType:false,onProgress:u.empty,onSuccess:u.empty,onError:u.empty,onAbort:u.empty,onComplete:u.empty},k||{});this.initXHR()};w.State={};["UNINITIALIZED","LOADING","LOADED","INTERACTIVE","COMPLETED"].forEach(function(k,f){w.State[k]=f});w.prototype={initXHR:function(){var k=this.req=new XMLHttpRequest,f=this;["Progress","Error","Abort","Load"].forEach(function(d){if(k.addEventListener)k.addEventListener(d.toLowerCase(),
function(h){f["handle"+d](h)},false);else k["on"+d.toLowerCase()]=function(h){f["handle"+d](h)}})},send:function(k){var f=this.req,d=this.opt,h=d.async;if(d.noCache)d.url+=(d.url.indexOf("?")>=0?"&":"?")+u.uid();f.open(d.method,d.url,h);if(d.responseType)f.responseType=d.responseType;if(h)f.onreadystatechange=function(){if(f.readyState==w.State.COMPLETED)if(f.status==200)d.onSuccess(f.responseType?f.response:f.responseText);else d.onError(f.status)};d.sendAsBinary?f.sendAsBinary(k||d.body||null):
f.send(k||d.body||null);if(!h)if(f.status==200)d.onSuccess(f.responseType?f.response:f.responseText);else d.onError(f.status)},setRequestHeader:function(k,f){this.req.setRequestHeader(k,f);return this},handleProgress:function(k){if(k.lengthComputable)this.opt.onProgress(k,Math.round(k.loaded/k.total*100));else this.opt.onProgress(k,-1)},handleError:function(k){this.opt.onError(k)},handleAbort:function(){this.opt.onAbort(e)},handleLoad:function(k){this.opt.onComplete(k)}};w.Group=function(k){function f(j){return function(l){--c;
k.onError(l,j);if(!c)k.onComplete(i)}}function d(j){return function(l){--c;i[j]=l;k.onSuccess(l,j);if(!c)k.onComplete(i)}}k=u.merge({urls:[],onError:u.empty,onSuccess:u.empty,onComplete:u.empty,method:"GET",async:true,noCache:false,sendAsBinary:false,responseType:false},k||{});var h=u.splat(k.urls),c=h.length,i=Array(c);this.reqs=h.map(function(j,l){return new w({url:j,method:k.method,async:k.async,noCache:k.noCache,sendAsBinary:k.sendAsBinary,responseType:k.responseType,body:k.body,onError:f(l),
onSuccess:d(l)})})};w.Group.prototype={send:function(){for(var k=0,f=this.reqs,d=f.length;k<d;++k)f[k].send()}};var m=function(k){k=u.merge({url:"http://philogljs.org/",data:{},noCache:false,onComplete:u.empty,callbackKey:"callback"},k||{});var f=m.counter++,d=[],h;for(h in k.data)d.push(h+"="+k.data[h]);d=d.join("&");if(k.noCache)d+=(d.indexOf("?")>=0?"&":"?")+u.uid();d=k.url+(k.url.indexOf("?")>-1?"&":"?")+k.callbackKey+"=PhiloGL.IO.JSONP.requests.request_"+f+(d.length>0?"&"+d:"");var c=document.createElement("script");
c.type="text/javascript";c.src=d;m.requests["request_"+f]=function(i){k.onComplete(i);c.parentNode&&c.parentNode.removeChild(c);c.clearAttributes&&c.clearAttributes()};document.getElementsByTagName("head")[0].appendChild(c)};m.counter=0;m.requests={};var o=function(k){k=u.merge({src:[],noCache:false,onProgress:u.empty,onComplete:u.empty},k||{});var f=0,d=k.src.length,h=function(){k.onProgress(Math.round(++f/d*100));if(f==d)k.onComplete(l)},c=function(){if(++f==d)k.onComplete(l)},i=k.noCache,j=u.uid(),
l=k.src.map(function(r,x){var t=new Image;t.index=x;t.onload=h;t.onerror=c;t.src=r+(i?(r.indexOf("?")>=0?"&":"?")+j:"");return t});return l};z.XHR=w;z.JSONP=m;z.Images=o;z.Textures=function(k){k=u.merge({src:[],noCache:false,onComplete:u.empty},k||{});o({src:k.src,noCache:k.noCache,onComplete:function(f){var d={};f.forEach(function(h,c){d[k.id&&k.id[c]||k.src&&k.src[c]]=u.merge({data:{value:h}},k)});M.setTextures(d);k.onComplete()}})};PhiloGL.IO=z})();(function(){var z=PhiloGL.Vec3,w=PhiloGL.Mat4,
m=function(o,k,f,d,h){h=h||{};var c=h.position,i=h.target,j=h.up;this.type=h.type?h.type:"perspective";this.fov=o;this.near=f;this.far=d;this.aspect=k;this.position=c&&new z(c.x,c.y,c.z)||new z;this.target=i&&new z(i.x,i.y,i.z)||new z;this.up=j&&new z(j.x,j.y,j.z)||new z(0,1,0);if(this.type=="perspective")this.projection=(new w).perspective(o,k,f,d);else{o=f*Math.tan(o*Math.PI/360);h=-o;this.projection=(new w).ortho(h*k,o*k,h,o,f,d)}this.view=new w};m.prototype={update:function(){if(this.type=="perspective")this.projection=
(new w).perspective(this.fov,this.aspect,this.near,this.far);else{var o=this.near*Math.tan(this.fov*Math.PI/360),k=-o,f=k*this.aspect,d=o*this.aspect;this.projection=(new w).ortho(f,d,k,o,this.near,this.far)}this.view.lookAt(this.position,this.target,this.up)},setStatus:function(o){var k=this.position,f=this.view,d=this.projection,h=f.mulMat4(d),c=h.invert();o.setUniforms({cameraPosition:[k.x,k.y,k.z],projectionMatrix:d,viewMatrix:f,viewProjectionMatrix:h,viewInverseMatrix:f.invert(),viewProjectionInverseMatrix:c})}};
PhiloGL.Camera=m})();(function(){function z(c,i){if(c&&c.length<i){for(var j=c[0],l=c[1],r=c[2],x=c[3],t=[j,l,r,x],A=i/c.length,a;--A;){a=A*4;t[a]=j;t[a+1]=l;t[a+2]=r;t[a+3]=x}return new Float32Array(t)}else return c}var w=PhiloGL.Vec3,m=PhiloGL.Mat4,o=Math.cos,k=Math.sin,f=Math.PI,d=Array.prototype.slice,h={attributeMap:{position:"vertices",normal:"normals",pickingColor:"pickingColors",colors:"color"}};h.Model=function(c){c=c||{};this.id=c.id||u.uid();this.pickable=!!c.pickable;this.pick=c.pick||
function(){return false};this.vertices=c.vertices;this.normals=c.normals;this.textures=c.textures&&u.splat(c.textures);this.colors=c.colors;this.indices=c.indices;this.shininess=c.shininess||0;this.reflection=c.reflection||0;this.refraction=c.refraction||0;if(c.pickingColors)this.pickingColors=c.pickingColors;if(c.texCoords)this.texCoords=c.texCoords;this.uniforms=c.uniforms||{};this.attributes=c.attributes||{};this.render=c.render;this.drawType=c.drawType||"TRIANGLES";this.display="display"in c?
c.display:true;this.onBeforeRender=c.onBeforeRender||u.empty;this.onAfterRender=c.onAfterRender||u.empty;if(c.program)this.program=c.program;this.position=new w;this.rotation=new w;this.scale=new w(1,1,1);this.matrix=new m;c.computeCentroids&&this.computeCentroids();c.computeNormals&&this.computeNormals()};h.Model.prototype=Object.create(null,{hash:{get:function(){return this.id+" "+this.$pickingIndex}},vertices:{set:function(c){if(c){var i=c.length;if(c.BYTES_PER_ELEMENT)this.$vertices=c;else if(this.$verticesLength==
i)this.$vertices.set(c);else this.$vertices=new Float32Array(c);this.$verticesLength=i}else{delete this.$vertices;delete this.$verticesLength}},get:function(){return this.$vertices}},normals:{set:function(c){if(c){var i=c.length;if(c.BYTES_PER_ELEMENT)this.$normals=c;else if(this.$normalsLength==i)this.$normals.set(c);else this.$normals=new Float32Array(c);this.$normalsLength=i}else{delete this.$normals;delete this.$normalsLength}},get:function(){return this.$normals}},colors:{set:function(c){if(c){var i=
c.length;if(c.BYTES_PER_ELEMENT)this.$colors=c;else if(this.$colorsLength==i)this.$colors.set(c);else this.$colors=new Float32Array(c);if(this.$vertices&&this.$verticesLength/3*4!=i)this.$colors=z(d.call(this.$colors),this.$verticesLength/3*4);this.$colorsLength=this.$colors.length}else{delete this.$colors;delete this.$colorsLength}},get:function(){return this.$colors}},pickingColors:{set:function(c){if(c){var i=c.length;if(c.BYTES_PER_ELEMENT)this.$pickingColors=c;else if(this.$pickingColorsLength==
i)this.$pickingColors.set(c);else this.$pickingColors=new Float32Array(c);if(this.$vertices&&this.$verticesLength/3*4!=i)this.$pickingColors=z(d.call(this.$pickingColors),this.$verticesLength/3*4);this.$pickingColorsLength=this.$pickingColors.length}else{delete this.$pickingColors;delete this.$pickingColorsLength}},get:function(){return this.$pickingColors}},texCoords:{set:function(c){if(c)if(u.type(c)=="object"){var i={},j;for(j in c){var l=c[j];i[j]=l.BYTES_PER_ELEMENT?l:new Float32Array(l)}this.$texCoords=
i}else{i=c.length;if(c.BYTES_PER_ELEMENT)this.$texCoords=c;else if(this.$texCoordsLength==i)this.$texCoords.set(c);else this.$texCoords=new Float32Array(c);this.$texCoordsLength=i}else{delete this.$texCoords;delete this.$texCoordsLength}},get:function(){return this.$texCoords}},indices:{set:function(c){if(c){var i=c.length;if(c.BYTES_PER_ELEMENT)this.$indices=c;else if(this.$indicesLength==i)this.$indices.set(c);else this.$indices=new Uint16Array(c);this.$indicesLength=i}else{delete this.$indices;
delete this.$indicesLength}},get:function(){return this.$indices}}});u.extend(h.Model.prototype,{$$family:"model",update:function(){var c=this.matrix,i=this.position,j=this.rotation,l=this.scale;c.id();c.$translate(i.x,i.y,i.z);c.$rotateXYZ(j.x,j.y,j.z);c.$scale(l.x,l.y,l.z)},computeCentroids:function(){var c=this.vertices,i=[];this.faces.forEach(function(j){var l=[0,0,0],r=0;j.forEach(function(x){x=c[x];l[0]+=x[0];l[1]+=x[1];l[2]+=x[2];r++});l[0]/=r;l[1]/=r;l[2]/=r;i.push(l)});this.centroids=i},
computeNormals:function(){var c=this.vertices,i=[];this.faces.forEach(function(j){var l=c[j[0]],r=c[j[1]];j=c[j[2]];l={x:l[0]-r[0],y:l[1]-r[1],z:l[2]-r[2]};w.$cross(l,{x:j[0]-r[0],y:j[1]-r[1],z:j[1]-r[2]});w.norm(l)>1.0E-6&&w.unit(l);i.push([l.x,l.y,l.z])});this.normals=i}});u.extend(h.Model.prototype,{setUniforms:function(c){c.setUniforms(this.uniforms)},setAttributes:function(c){var i=this.attributes,j;for(j in i){var l=i[j],r=this.id+"-"+j;if(Object.keys(l).length){l.attribute=j;c.setBuffer(r,
l);delete l.value}else c.setBuffer(r,true)}},setVertices:function(c){if(this.$vertices)this.dynamic?c.setBuffer("position-"+this.id,{attribute:"position",value:this.$vertices,size:3}):c.setBuffer("position-"+this.id)},setNormals:function(c){if(this.$normals)this.dynamic?c.setBuffer("normal-"+this.id,{attribute:"normal",value:this.$normals,size:3}):c.setBuffer("normal-"+this.id)},setIndices:function(c){if(this.$indices)this.dynamic?c.setBuffer("indices-"+this.id,{bufferType:p.ELEMENT_ARRAY_BUFFER,
drawType:p.STATIC_DRAW,value:this.$indices,size:1}):c.setBuffer("indices-"+this.id)},setPickingColors:function(c){if(this.$pickingColors)this.dynamic?c.setBuffer("pickingColor-"+this.id,{attribute:"pickingColor",value:this.$pickingColors,size:4}):c.setBuffer("pickingColor-"+this.id)},setColors:function(c){if(this.$colors)this.dynamic?c.setBuffer("color-"+this.id,{attribute:"color",value:this.$colors,size:4}):c.setBuffer("color-"+this.id)},setTexCoords:function(c){if(this.$texCoords){var i=this.id,
j,l,r,x;if(this.dynamic)if(u.type(this.$texCoords)=="object"){j=0;l=this.textures;for(r=l.length;j<r;j++){x=l[j];c.setBuffer("texCoord-"+j+"-"+i,{attribute:"texCoord"+(j+1),value:this.$texCoords[x],size:2})}}else c.setBuffer("texCoord-"+i,{attribute:"texCoord1",value:this.$texCoords,size:2});else if(u.type(this.$texCoords)=="object"){j=0;l=this.textures;for(r=l.length;j<r;j++)c.setBuffer("texCoord-"+j+"-"+i)}else c.setBuffer("texCoord-"+i)}},setTextures:function(c){this.textures=this.textures?u.splat(this.textures):
[];for(var i=0,j=this.textures,l=j.length,r=PhiloGL.Scene.MAX_TEXTURES;i<r;i++){if(i<l)if(M.textureMemo[j[i]].isCube){c.setUniform("hasTextureCube"+(i+1),true);c.setTexture(j[i],p["TEXTURE"+(i+5)])}else{c.setUniform("hasTexture"+(i+1),true);c.setTexture(j[i],p["TEXTURE"+i])}else{c.setUniform("hasTextureCube"+(i+1),false);c.setUniform("hasTexture"+(i+1),false)}c.setUniform("sampler"+(i+1),i);c.setUniform("samplerCube"+(i+1),i+5)}},setState:function(c){this.setUniforms(c);this.setAttributes(c);this.setVertices(c);
this.setColors(c);this.setPickingColors(c);this.setNormals(c);this.setTextures(c);this.setTexCoords(c);this.setIndices(c)},unsetState:function(c){c=c.attributes;p.bindBuffer(p.ARRAY_BUFFER,null);p.bindBuffer(p.ELEMENT_ARRAY_BUFFER,null);for(var i in c)p.disableVertexAttribArray(c[i])}});h.Cube=function(c){h.Model.call(this,u.extend({vertices:[-1,-1,1,1,-1,1,1,1,1,-1,1,1,-1,-1,-1,-1,1,-1,1,1,-1,1,-1,-1,-1,1,-1,-1,1,1,1,1,1,1,1,-1,-1,-1,-1,1,-1,-1,1,-1,1,-1,-1,1,1,-1,-1,1,1,-1,1,1,1,1,-1,1,-1,-1,-1,
-1,-1,1,-1,1,1,-1,1,-1],texCoords:[0,0,1,0,1,1,0,1,1,0,1,1,0,1,0,0,0,1,0,0,1,0,1,1,1,1,0,1,0,0,1,0,1,0,1,1,0,1,0,0,0,0,1,0,1,1,0,1],normals:[0,0,1,0,0,1,0,0,1,0,0,1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,1,0,0,1,0,0,1,0,0,1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,1,0,0,1,0,0,1,0,0,1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,0],indices:[0,1,2,0,2,3,4,5,6,4,6,7,8,9,10,8,10,11,12,13,14,12,14,15,16,17,18,16,18,19,20,21,22,20,22,23]},c||{}))};h.Cube.prototype=Object.create(h.Model.prototype);h.Sphere=function(c){var i=c.nlat||10,j=
c.nlong||10,l=c.radius||1,r=f-0,x=2*f-0,t=(i+1)*(j+1),A=new Float32Array(t*3),a=new Float32Array(t*3);t=new Float32Array(t*2);var b=new Uint16Array(i*j*6);if(typeof l=="number"){var g=l;l=function(){return g}}for(var n=0;n<=i;n++)for(var q=0;q<=j;q++){var s=q/j,v=n/i,y=x*s,B=r*v,C=k(y);y=o(y);var D=k(B),E=o(B);B=y*D;y=E;C*=D;D=l(B,y,C,s,v);E=q+n*(j+1);var G=E*3;E*=2;A[G+0]=D*B;A[G+1]=D*y;A[G+2]=D*C;a[G+0]=B;a[G+1]=y;a[G+2]=C;t[E+0]=s;t[E+1]=v}l=i+1;for(q=0;q<i;q++)for(n=0;n<j;n++){E=(q*j+n)*6;b[E+
0]=n*l+q;b[E+1]=n*l+q+1;b[E+2]=(n+1)*l+q;b[E+3]=(n+1)*l+q;b[E+4]=n*l+q+1;b[E+5]=(n+1)*l+q+1}h.Model.call(this,u.extend({vertices:A,indices:b,normals:a,texCoords:t},c||{}))};h.Sphere.prototype=Object.create(h.Model.prototype);h.IcoSphere=function(c){var i=c.iterations||0,j=[],l=[],r=Math.sqrt,x=Math.acos,t=Math.atan2,A=Math.PI,a=A*2;c.onAddVertex=c.onAddVertex||u.empty;var b=(1+r(5))/2,g=r(1+b*b);j.push(-1/g,b/g,0,1/g,b/g,0,-1/g,-b/g,0,1/g,-b/g,0,0,-1/g,b/g,0,1/g,b/g,0,-1/g,-b/g,0,1/g,-b/g,b/g,0,-1/
g,b/g,0,1/g,-b/g,0,-1/g,-b/g,0,1/g);l.push(0,11,5,0,5,1,0,1,7,0,7,10,0,10,11,1,5,9,5,11,4,11,10,2,10,7,6,7,1,8,3,9,4,3,4,2,3,2,6,3,6,8,3,8,9,4,9,5,2,4,11,6,2,10,8,6,7,9,8,1);var n=function(){var W={};return function(S,T){S*=3;T*=3;var X=(S<T?S:T)+"|"+(S>T?S:T);if(X in W)return W[X];var O=(j[S]+j[T])/2,Y=(j[S+1]+j[T+1])/2,Z=(j[S+2]+j[T+2])/2,$=r(O*O+Y*Y+Z*Z);O/=$;Y/=$;Z/=$;j.push(O,Y,Z);return W[X]=j.length/3-1}}();for(b=0;b<i;b++){var q=[],s=0;for(g=l.length;s<g;s+=3){var v=n(l[s],l[s+1]),y=n(l[s+
1],l[s+2]),B=n(l[s+2],l[s]);q.push(l[s],v,B,l[s+1],y,v,l[s+2],B,y,v,y,B)}l=q}g=l.length;i=new Float32Array(g*3);n=new Float32Array(g*2);for(b=0;b<g;b+=3){y=l[b];B=l[b+1];var C=l[b+2];q=y*3;s=B*3;v=C*3;y*=2;B*=2;C*=2;var D=j[q],E=j[q+1],G=j[q+2],I=x(G/r(D*D+E*E+G*G)),J=t(E,D);I/=A;J=1-J/a;var H=j[s],F=j[s+1],N=j[s+2],K=x(N/r(H*H+F*F+N*N)),L=t(F,H);K/=A;L=1-L/a;var P=j[v],Q=j[v+1],R=j[v+2],U=x(R/r(P*P+Q*Q+R*R)),V=t(Q,P);U/=A;V=1-V/a;D=w.cross({x:P-H,y:Q-F,z:R-N},{x:D-H,y:E-F,z:G-N}).$unit();i[q]=i[s]=
i[v]=D.x;i[q+1]=i[s+1]=i[v+1]=D.y;i[q+2]=i[s+2]=i[v+2]=D.z;n[y]=J;n[y+1]=I;n[B]=L;n[B+1]=K;n[C]=V;n[C+1]=U}h.Model.call(this,u.extend({vertices:j,indices:l,normals:i,texCoords:n},c||{}))};h.IcoSphere.prototype=Object.create(h.Model.prototype);h.TruncatedCone=function(c){var i=c.bottomRadius||0,j=c.topRadius||0,l=c.height||1,r=c.nradial||10,x=c.nvertical||10,t=!!c.topCap,A=!!c.bottomCap,a=(t?2:0)+(A?2:0),b=(r+1)*(x+1+a),g=new Float32Array(b*3),n=new Float32Array(b*3);b=new Float32Array(b*2);var q=
new Uint16Array(r*(x+a)*6),s=r+1,v=Math,y=v.atan2(i-j,l),B=v.sin,C=v.cos;v=v.PI;var D=C(y);y=B(y);A=x+(A?2:0);var E=0,G=0;for(t=t?-2:0;t<=A;t++){var I=t/x,J=l*I,H;if(t<0){J=0;I=1;H=i}else if(t>x){J=l;I=1;H=j}else H=i+(j-i)*(t/x);if(t==-2||t==x+2)I=H=0;J-=l/2;for(var F=0;F<s;F++){var N=B(F*v*2/r),K=C(F*v*2/r);g[E+0]=N*H;g[E+1]=J;g[E+2]=K*H;n[E+0]=t<0||t>x?0:N*D;n[E+1]=t<0?-1:t>x?1:y;n[E+2]=t<0||t>x?0:K*D;b[G+0]=F/r;b[G+1]=I;G+=2;E+=3}}for(t=0;t<x+a;t++)for(F=0;F<r;F++){i=(t*r+F)*6;q[i+0]=s*(t+0)+0+
F;q[i+1]=s*(t+0)+1+F;q[i+2]=s*(t+1)+1+F;q[i+3]=s*(t+0)+0+F;q[i+4]=s*(t+1)+1+F;q[i+5]=s*(t+1)+0+F}h.Model.call(this,u.extend({vertices:g,normals:n,texCoords:b,indices:q},c||{}))};h.TruncatedCone.prototype=Object.create(h.Model.prototype);h.Cone=function(c){c.topRadius=0;c.topCap=!!c.cap;c.bottomCap=!!c.cap;c.bottomRadius=c.radius||3;h.TruncatedCone.call(this,c)};h.Cone.prototype=Object.create(h.TruncatedCone.prototype);h.Cylinder=function(c){c.bottomRadius=c.radius;c.topRadius=c.radius;h.TruncatedCone.call(this,
c)};h.Cylinder.prototype=Object.create(h.TruncatedCone.prototype);h.Plane=function(c){var i=c.type,j=i.split(","),l=c[j[0]+"len"],r=c[j[1]+"len"],x=c["n"+j[0]]||1;j=c["n"+j[1]]||1;var t=c.offset,A=!!c.flipCull,a=(x+1)*(j+1),b=new Float32Array(a*3),g=new Float32Array(a*3);a=new Float32Array(a*2);var n=0,q=0;if(A)l=-l;for(var s=0;s<=j;s++)for(var v=0;v<=x;v++){var y=v/x,B=s/j;a[n+0]=A?1-y:y;a[n+1]=B;n+=2;switch(i){case "x,y":b[q+0]=l*y-l*0.5;b[q+1]=r*B-r*0.5;b[q+2]=t;g[q+0]=0;g[q+1]=0;g[q+2]=A?1:-1;
break;case "x,z":b[q+0]=l*y-l*0.5;b[q+1]=t;b[q+2]=r*B-r*0.5;g[q+0]=0;g[q+1]=A?1:-1;g[q+2]=0;break;case "y,z":b[q+0]=t;b[q+1]=l*y-l*0.5;b[q+2]=r*B-r*0.5;g[q+0]=A?1:-1;g[q+1]=0;g[q+2]=0}q+=3}i=x+1;l=[];for(s=0;s<j;s++)for(v=0;v<x;v++){r=(s*x+v)*6;l[r+0]=(s+0)*i+v;l[r+1]=(s+1)*i+v;l[r+2]=(s+0)*i+v+1;l[r+3]=(s+1)*i+v;l[r+4]=(s+1)*i+v+1;l[r+5]=(s+0)*i+v+1}h.Model.call(this,u.extend({vertices:b,normals:g,texCoords:a,indices:l},c))};h.Plane.prototype=Object.create(h.Model.prototype);h.id=u.time();PhiloGL.O3D=
h})();(function(){var z={Vertex:{},Fragment:{}},w=z.Fragment;z.Vertex.Default="#define LIGHT_MAX 4\nattribute vec3 position;\nattribute vec3 normal;\nattribute vec4 color;\nattribute vec4 pickingColor;\nattribute vec2 texCoord1;\nuniform mat4 viewMatrix;\nuniform mat4 viewInverseMatrix;\nuniform mat4 projectionMatrix;\nuniform mat4 viewProjectionMatrix;\nuniform mat4 worldMatrix;\nuniform mat4 worldInverseMatrix;\nuniform mat4 worldInverseTransposeMatrix;\nuniform mat4 objectMatrix;\nuniform vec3 cameraPosition;\nuniform bool enableLights;\nuniform vec3 ambientColor;\nuniform vec3 directionalColor;\nuniform vec3 lightingDirection;\nuniform vec3 pointLocation[LIGHT_MAX];\nuniform vec3 pointColor[LIGHT_MAX];\nuniform int numberPoints;\nuniform bool useReflection;\nvarying vec3 vReflection;\nvarying vec4 vColor;\nvarying vec4 vPickingColor;\nvarying vec2 vTexCoord;\nvarying vec4 vNormal;\nvarying vec3 lightWeighting;\nvoid main(void) {\nvec4 mvPosition = worldMatrix * vec4(position, 1.0);\nvec4 transformedNormal = worldInverseTransposeMatrix * vec4(normal, 1.0);\nif(!enableLights) {\nlightWeighting = vec3(1.0, 1.0, 1.0);\n} else {\nvec3 plightDirection;\nvec3 pointWeight = vec3(0.0, 0.0, 0.0);\nfloat directionalLightWeighting = max(dot(transformedNormal.xyz, lightingDirection), 0.0);\nfor (int i = 0; i < LIGHT_MAX; i++) {\nif (i < numberPoints) {\nplightDirection = normalize((viewMatrix * vec4(pointLocation[i], 1.0)).xyz - mvPosition.xyz);\npointWeight += max(dot(transformedNormal.xyz, plightDirection), 0.0) * pointColor[i];\n} else {\nbreak;\n}\n}\nlightWeighting = ambientColor + (directionalColor * directionalLightWeighting) + pointWeight;\n}\nif (useReflection) {\nvReflection = (viewInverseMatrix[3] - (worldMatrix * vec4(position, 1.0))).xyz;\n} else {\nvReflection = vec3(1.0, 1.0, 1.0);\n}\nvColor = color;\nvPickingColor = pickingColor;\nvTexCoord = texCoord1;\nvNormal = transformedNormal;\ngl_Position = projectionMatrix * worldMatrix * vec4(position, 1.0);\n}";
w.Default="#ifdef GL_ES\nprecision highp float;\n#endif\nvarying vec4 vColor;\nvarying vec4 vPickingColor;\nvarying vec2 vTexCoord;\nvarying vec3 lightWeighting;\nvarying vec3 vReflection;\nvarying vec4 vNormal;\nuniform bool hasTexture1;\nuniform sampler2D sampler1;\nuniform bool hasTextureCube1;\nuniform samplerCube samplerCube1;\nuniform bool enablePicking;\nuniform bool hasPickingColors;\nuniform vec3 pickColor;\nuniform float reflection;\nuniform float refraction;\nuniform bool hasFog;\nuniform vec3 fogColor;\nuniform float fogNear;\nuniform float fogFar;\nvoid main(){\nif (!hasTexture1) {\ngl_FragColor = vec4(vColor.rgb * lightWeighting, vColor.a);\n} else {\ngl_FragColor = vec4(texture2D(sampler1, vec2(vTexCoord.s, vTexCoord.t)).rgb * lightWeighting, 1.0);\n}\nif (hasTextureCube1) {\nvec3 nReflection = normalize(vReflection);\nvec3 reflectionValue;\nif (refraction > 0.0) {\nreflectionValue = refract(nReflection, vNormal.xyz, refraction);\n} else {\nreflectionValue = -reflect(nReflection, vNormal.xyz);\n}\nvec4 cubeColor = textureCube(samplerCube1, vec3(-reflectionValue.x, -reflectionValue.y, reflectionValue.z));\ngl_FragColor = vec4(mix(gl_FragColor.xyz, cubeColor.xyz, reflection), 1.0);\n}\nif (enablePicking) {\nif (hasPickingColors) {\ngl_FragColor = vPickingColor;\n} else {\ngl_FragColor = vec4(pickColor, 1.0);\n}\n}\nif (hasFog) {\nfloat depth = gl_FragCoord.z / gl_FragCoord.w;\nfloat fogFactor = smoothstep(fogNear, fogFar, depth);\ngl_FragColor = mix(gl_FragColor, vec4(fogColor, gl_FragColor.w), fogFactor);\n}\n}";
PhiloGL.Shaders=z})();(function(){var z=PhiloGL.Vec3,w=function(m,o,k){k=u.merge({lights:{enable:false,ambient:{r:0.2,g:0.2,b:0.2},directional:{direction:{x:1,y:1,z:1},color:{r:0,g:0,b:0}}},effects:{fog:false}},k||{});this.program=k.program?m[k.program]:m;this.camera=o;this.models=[];this.config=k};w.prototype={add:function(){for(var m=0,o=this.models,k=arguments.length;m<k;m++){var f=arguments[m];f.id=f.id||u.uid();o.push(f);this.defineBuffers(f)}},remove:function(m){var o=this.models;m=o.indexOf(m);
m>-1&&o.splice(m,1)},getProgram:function(m){var o=this.program;if(o.$$family!="program"&&m&&m.program){o=o[m.program];o.use()}return o},defineBuffers:function(m){var o=this.getProgram(m),k=m.dynamic;m.dynamic=true;m.setState(o);m.dynamic=k;m.unsetState(o)},beforeRender:function(m){this.setupLighting(m);this.setupEffects(m);this.camera&&this.camera.setStatus(m)},setupLighting:function(m){var o=this.config.lights,k=o.ambient,f=o.directional,d=f.color,h=f.direction,c=o.enable;o=o.points&&u.splat(o.points)||
[];f=o.length;var i=[],j=[],l=[],r=[];h=(new z(h.x,h.y,h.z)).$unit().$scale(-1);m.setUniform("enableLights",c);if(c){m.setUniform("ambientColor",[k.r,k.g,k.b]);m.setUniform("directionalColor",[d.r,d.g,d.b]);m.setUniform("lightingDirection",[h.x,h.y,h.z]);m.setUniform("numberPoints",f);for(k=0;k<f;k++){c=o[k];d=c.position;h=c.color||c.diffuse;c=c.specular;i.push(d.x,d.y,d.z);j.push(h.r,h.g,h.b);l.push(+!!c);c?r.push(c.r,c.g,c.b):r.push(0,0,0)}m.setUniforms({pointLocation:i,pointColor:j});m.setUniforms({enableSpecular:l,
pointSpecularColor:r})}},setupEffects:function(m){var o=this.config.effects.fog,k=o.color||{r:0.5,g:0.5,b:0.5};o?m.setUniforms({hasFog:true,fogNear:o.near,fogFar:o.far,fogColor:[k.r,k.g,k.b]}):m.setUniform("hasFog",false)},render:function(m){m=m||{};var o=this.camera,k=this.program,f=m.renderProgram,d=u.type(k);d=!f&&d=="object";m=u.extend({onBeforeRender:u.empty,onAfterRender:u.empty},m||{});!d&&this.beforeRender(f||k);for(var h=0,c=this.models,i=c.length;h<i;++h){var j=c[h];if(j.display){k=f||this.getProgram(j);
d&&this.beforeRender(k);j.onBeforeRender(k,o);m.onBeforeRender(j,h);this.renderObject(j,k);m.onAfterRender(j,h);j.onAfterRender(k,o)}}},renderToTexture:function(m,o){o=o||{};var k=M.textures[m+"-texture"],f=M.textureMemo[m+"-texture"];this.render(o);p.bindTexture(f.textureType,k)},renderObject:function(m,o){var k=this.camera,f=m.matrix,d=k.view.mulMat4(f),h=d.invert(),c=h.transpose();m.setState(o);o.setUniforms({objectMatrix:f,worldMatrix:d,worldInverseMatrix:h,worldInverseTransposeMatrix:c});if(m.render)m.render(p,
o,k);else m.$indicesLength?p.drawElements(m.drawType!==undefined?p.get(m.drawType):p.TRIANGLES,m.$indicesLength,p.UNSIGNED_SHORT,0):p.drawArrays(m.drawType!==undefined?p.get(m.drawType):p.TRIANGLES,0,m.$verticesLength/3);m.unsetState(o)},setupPicking:function(){var m=PhiloGL.Program.fromDefaultShaders();M.setFrameBuffer("$picking",{width:5,height:1,bindToTexture:{parameters:[{name:"TEXTURE_ MAG_FILTER",value:"LINEAR"},{name:"TEXTURE_MIN_FILTER",value:"LINEAR",generateMipmap:false}]},bindToRenderBuffer:true});
M.setFrameBuffer("$picking",false);this.pickingProgram=m},pick:function(m,o){this.pickingProgram||this.setupPicking();var k={},f=[],d=M.usedProgram,h=this.pickingProgram,c=this.camera,i=c.target,j=c.aspect,l=this.config,r=l.lights.enable,x=l.effects.fog,t=p.canvas.width,A=p.canvas.height,a=this.unproject([m*2/t-1,1-o*2/A,1],c),b=new Uint8Array(4);this.camera.target=a;this.camera.update();l.lights.enable=false;l.effects.fog=false;M.setFrameBuffer("$picking",true);h.use();h.setUniform("enablePicking",
true);p.disable(p.BLEND);p.viewport(0,0,5,1);p.clear(p.COLOR_BUFFER_BIT|p.DEPTH_BUFFER_BIT);p.readPixels(0,0,1,1,p.RGBA,p.UNSIGNED_BYTE,b);this.renderPickingScene({background:b[0]+b[1]*256+b[2]*65536,o3dHash:k,o3dList:f,hash:[]});p.readPixels(2,0,1,1,p.RGBA,p.UNSIGNED_BYTE,b);a=[b[0],b[1],b[2]].join();a=k[a];var g;if(!a)for(var n=0,q=f.length;n<q;n++){a=f[n];g=a.pick(b);if(g!==false)a.$pickingIndex=g;else a=false}M.setFrameBuffer("$picking",false);M.setTexture("$picking-texture",false);h.setUniform("enablePicking",
false);l.lights.enable=r;l.effects.fog=x;d&&d.use();p.viewport(0,0,t,A);c.target=i;c.aspect=j;c.update();this.o3dHash=k;this.o3dList=f;this.pixel=b;this.capture=void 0;return a&&a.pickable&&a},unproject:function(m,o){return o.view.invert().mulMat4(o.projection.invert()).mulVec3(m)},renderPickingScene:function(m){if(this.config.renderPickingScene)this.config.renderPickingScene.call(this,m);else{var o=this.pickingProgram,k=m.o3dHash,f=m.o3dList,d=m.background,h=m.hash,c=0;this.renderToTexture("$picking",
{renderProgram:o,onBeforeRender:function(i,j){if(j==d)c=1;var l=j+c,r=!!i.pickingColors;o.setUniform("hasPickingColors",r);if(r)f.push(i);else{h[0]=l%256;h[1]=(l/256>>0)%256;h[2]=(l/65536>>0)%256;o.setUniform("pickColor",[h[0]/255,h[1]/255,h[2]/255]);k[h.join()]=i}}})}},resetPicking:u.empty};w.MAX_TEXTURES=10;w.MAX_POINT_LIGHTS=4;w.PICKING_RES=4;PhiloGL.Scene=w})();(function(){function z(w,m){for(var o=this.workers=[];m--;)o.push(new Worker(w))}z.prototype={map:function(w){var m=this.workers,o=this.configs=
[],k=0;for(m=m.length;k<m;k++)o.push(w&&w(k));return this},reduce:function(w){for(var m=w.reduceFn,o=this.workers,k=this.configs,f=o.length,d=w.initialValue,h=function(l){f--;d=d===undefined?l.data:m(d,l.data);if(f==0)w.onComplete(d)},c=0,i=f;c<i;c++){var j=o[c];j.onmessage=h;j.postMessage(k[c])}return this}};PhiloGL.WorkerGroup=z})();(function(){var z=function(d){this.opt=u.merge({delay:0,duration:1E3,transition:function(h){return h},onCompute:u.empty,onComplete:u.empty},d||{})},w=z.Queue=[];z.prototype=
{time:null,start:function(d){this.opt=u.merge(this.opt,d||{});this.time=u.time();this.animating=true;w.push(this)},step:function(){if(this.animating){var d=u.time(),h=this.time,c=this.opt,i=c.delay,j=c.duration,l=0;if(d<h+i)c.onCompute.call(this,l);else if(d<h+i+j){l=c.transition((d-h-i)/j);c.onCompute.call(this,l)}else{this.animating=false;c.onCompute.call(this,1);c.onComplete.call(this)}}}};z.compute=function(d,h,c){return d+(h-d)*c};z.Transition={linear:function(d){return d}};var m=z.Transition;
(function(){var d=function(i,j){j=u.splat(j);return u.extend(i,{easeIn:function(l){return i(l,j)},easeOut:function(l){return 1-i(1-l,j)},easeInOut:function(l){return l<=0.5?i(2*l,j)/2:(2-i(2*(1-l),j))/2}})},h={Pow:function(i,j){return Math.pow(i,j[0]||6)},Expo:function(i){return Math.pow(2,8*(i-1))},Circ:function(i){return 1-Math.sin(Math.acos(i))},Sine:function(i){return 1-Math.sin((1-i)*Math.PI/2)},Back:function(i,j){j=j[0]||1.618;return Math.pow(i,2)*((j+1)*i-j)},Bounce:function(i){for(var j,l=
0,r=1;;l+=r,r/=2)if(i>=(7-4*l)/11){j=r*r-Math.pow((11-6*l-11*i)/4,2);break}return j},Elastic:function(i,j){return Math.pow(2,10*--i)*Math.cos(20*i*Math.PI*(j[0]||1)/3)}},c;for(c in h)m[c]=d(h[c]);["Quad","Cubic","Quart","Quint"].forEach(function(i,j){m[i]=d(function(l){return Math.pow(l,[j+2])})})})();var o=self||window,k=function(){var d=[];if(w.length){for(var h=0,c=w.length,i;h<c;h++){i=w[h];i.step();i.animating&&d.push(i)}z.Queue=w=d}};if(o){var f=false;["webkitAnimationTime","mozAnimationTime",
"animationTime","webkitAnimationStartTime","mozAnimationStartTime","animationStartTime"].forEach(function(d){if(d in o){z.animationTime=function(){return o[d]};f=true}});if(!f)z.animationTime=u.time;f=false;["webkitRequestAnimationFrame","mozRequestAnimationFrame","requestAnimationFrame"].forEach(function(d){if(d in o){z.requestAnimationFrame=function(h){o[d](function(){k();h()})};f=true}});if(!f)z.requestAnimationFrame=function(d){setTimeout(function(){k();d()},1E3/60)}}PhiloGL.Fx=z})();(function(){var z=
{},w=function(){};w.postProcess=function(){var m=new PhiloGL.O3D.Plane({type:"x,y",xlen:1,ylen:1,offset:0}),o=new PhiloGL.Camera(45,1,0.1,500,{position:{x:0,y:0,z:1.205}}),k=new PhiloGL.Scene({},o);return function(f){var d=M.program.$$family?M.program:M.program[f.program],h=f.fromTexture?u.splat(f.fromTexture):[],c=f.toFrameBuffer,i=!!f.toScreen,j=f.width||M.canvas.width,l=f.height||M.canvas.height;o.aspect=f.aspectRatio?f.aspectRatio:Math.max(l/j,j/l);o.update();k.program=d;m.textures=h;m.program=
d;k.models.length||k.add(m);if(c){c in M.frameBufferMemo||M.setFrameBuffer(c,{width:j,height:l,bindToTexture:{parameters:[{name:"TEXTURE_MAG_FILTER",value:"LINEAR"},{name:"TEXTURE_MIN_FILTER",value:"LINEAR",generateMipmap:false}]},bindToRenderBuffer:false});d.use();M.setFrameBuffer(c,true);p.viewport(0,0,j,l);p.clear(p.COLOR_BUFFER_BIT|p.DEPTH_BUFFER_BIT);d.setUniforms(f.uniforms||{});k.renderToTexture(c);M.setFrameBuffer(c,false)}if(i){d.use();p.viewport(0,0,j,l);p.clear(p.COLOR_BUFFER_BIT|p.DEPTH_BUFFER_BIT);
d.setUniforms(f.uniforms||{});k.render()}return this}}();z.Image=w;PhiloGL.Media=z})()})();
